### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tweensContainer' of undefined 

### ISSUE THREAD

**Issue by dejardine** [julianshapiro/velocity#305]
A strange one:

"Uncaught TypeError: Cannot read property 'tweensContainer' of undefined"

I am trying to replacing content after push/pop state then fading in a div. Interestingly if I remove the 'replaceWith' call I don't get the error. Any ideas? Running Jquery 1.11.0 & velocity 0.11.9

```
$('.content-wrap').velocity({
        opacity: 1
    }, {
        duration: 800,
        easing: bezEasing,
        delay: 0,
        begin: function() {

            // Replace content

            $('#content').replaceWith(resp);

        },
        complete: function() {

            // Reinit Height match

            $('.office').matchHeight();
            $('.job').matchHeight();
            $('.person').matchHeight();
            $('.group-services').matchHeight();

            // Init

            init();
        }
    });
```

**Comment by sfcgeorge** [comment]
I had the same problem, so I confirm that removing an element before Velocity has finished causes this error, and the fix is `$element.velocity("stop")`

**Comment by 304NotModified** [comment]
This is still an issue. It's really difficult to fiddle, as it is a race condition.  Even with `stop` is sometimes doesn't work (guess ~1/1000 times). A JavaScript crash is really an issue with a fledged ajax application. 

Is it possible to never throw an exception on this? 

Please reopen.

**Comment by MattyBalaam** [comment]
Without hopefully being too rude, I'm not sure how you expect people to reproduce the problem to fix it without an example.

**Comment by Rycochet** [comment]
I worked out what the problem was caused by back when this first got reported - and after a couple of stupidly busy months I'm starting to get a little time to actually do personal coding again - hopefully the next month or two will get things moving and bypass this issue entirely by doing things a different way, so I'm not planning to reopen it - once the next version of Velocity is up for testing then it can be pointed at again if it's still happening - but like all of these, it really needs some sort of test / fiddle to prove it (and a proper test when we get to that stage would always be useful to help stop it happening) ;-)

**Comment by 304NotModified** [comment]
> Without hopefully being too rude, I'm not sure how you expect people to reproduce the problem to fix it without an example.

Well in some cases the reproduction isn't needed? If it's clear (dunno if that's the case) where an error in thrown, you can fix it?

**Comment by Rycochet** [comment]
It's not clear where the error actually is - but it's caused by removing the element from the DOM before Velocity has finished with it. Part of the todo list is to get rid of the jQuery dependancy, which I've got a feeling might fix this issue as I'm pretty sure that I've seen it at least once (in the far distant past) when doing something similar outside Velocity...

**Comment by 304NotModified** [comment]
Something like this? https://github.com/julianshapiro/velocity/pull/690

**Comment by Rycochet** [comment]
While that fixes it, that's not actually the source, so needs to be manually merged back in...

**Comment by 304NotModified** [comment]
Was also thinking about that. But where is the source?

**Comment by Rycochet** [comment]
Currently private - as soon as it's ready then it'll be going back up on here where it's open for everyone who wants to help :-)
