### ISSUE TITLE
Velocity with plain javascript does not operate if jQuery library is included

### ISSUE THREAD

**Issue by abacaj** [julianshapiro/velocity#328]
When using plain javascript velocity operates fine with the code below, but when including the jQuery library the following code no longer works and the console logs `Uncaught ReferenceError: Velocity is not defined`

According to the documentation this should work with or without jQuery.

This limits us... this means we cannot mix and match javascript with jQuery and velocity.

See this fiddle: http://jsfiddle.net/1d200vh4/7/

`var box = document.querySelector('.box');`
`Velocity(box, {
    scale: 2
}, {
    easing: "linear",
    duration: 500,
    loop: true
});`

**Comment by focomoso** [comment]
I'm doing something similar, writing a custom web component that uses velocity for animation and I won't know whether jQuery is installed until runtime. 

The trouble I'm having is that while
    if (window.jQuery) { var V = $.Velocity; } else { var V = Velocity; }
works, I have to check this again every time I use V because V(element, {stuff}) doesn't work if V is set to $.Velocity. 

Is there any way around this?

**Comment by Danita** [comment]
+1

**Comment by Rycochet** [comment]
See #722 for how to bypass this.

**Comment by lmj0011** [comment]
I have a feeling lots of Vuejs developers are going to be landing here
