### ISSUE TITLE
rotate3d support

### ISSUE THREAD

**Issue by AlexanderFlatscher** [julianshapiro/velocity#350]
First of all, I love velocity.js

I need to do a flip animation from an element's corner (diagonal), like http://codepen.io/anon/pen/OPLomV

pretty easy with transform: rotate3d(45, 45, 0 180deg);
any way one can do that with velocity?

**Comment by julianshapiro** [comment]
because there's no independent transform property for animating the fourth component (angle) of rotate3d, i can't implement this without some sort of complete overhaul of my matrix manipulation code. i'll link to this in a related thread, but not sure what the chances are of inclusion. 

thanks again for bringing this up, alexander. super appreciated.

**Comment by danieldunderfelt** [comment]
Aww this feature would be great to have! But I understand why it would be hard to do.
