### ISSUE TITLE
Scrolling a container by an arbitrary value broken

### ISSUE THREAD

**Issue by slyngbaek** [julianshapiro/velocity#374]
When scrolling a container by an arbitrary value, it seems the container property must also be specified:

```javascript
/* Scroll a container by an arbitrary value. */
$("#container").velocity("scroll", { offset: "750px", container: $("#container") });
```

However, when scrolling a container by an arbitrary value while also changing the height of the container the scroll offset is incorrect.

```javascript
$("#container")
   .velocity("scroll", { offset: "750px", container: $("#container"), queue: false })
   .velocity({ height: "*=2" });
```

The scroll offset seems tied to the height of the container. Is there a more preferred way to scroll a container either by an offset or to an offset?

**Comment by julianshapiro** [comment]
Hey, @slyngbaek. Great question.

Velocity's scroll animation code doesn't rely on height (or any dimensions) explicitly. If concurrent height animation is affecting scroll animation, it has to do with the scrollOffset values the browser is providing me. 

Since this is a rare use case, I don't plan on overhauling Velocity's scroll implementation to accommodate such a workaround (if it's even possible), although if someone wants to take a stab at it -- I'm all ears!

Thanks again :)

**Comment by julianshapiro** [comment]
And, no, I don't know how else you would accomplish this unfortunately.
