### ISSUE TITLE
Artificial framerate throttling

### ISSUE THREAD

**Issue by weepy** [julianshapiro/velocity#418]
Hi,

Is it possible to run velocity at 30fps (for slower devices) ?

**Comment by ydaniv** [comment]
Currently no, there's no throttling OOTB in Velocity, AFAIK.

But I think adding it or at the very least allow a custom `ticker` would be quite simple to add.

@julianshapiro thoughts?

**Comment by julianshapiro** [comment]
This is a really interesting idea. Going to label it and look into it within <3wks.

**Comment by julianshapiro** [comment]
Been thinking about this from a meta perspective. I think you should just remove animations altogether if you're willing to have choppy animations; just switch to instant styling changes via CSS.

**Comment by weepy** [comment]
30fps isn't choppy at all

**Comment by julianshapiro** [comment]
Anyone else have thoughts on this? Leaving this open for now.

**Comment by Rycochet** [comment]
I can see two places this would be useful - the first is with colours, as the eye isn't as good at detecting colour changes as it is at detecting movement. The second is when it's animating something that causes a lot of cpu use - I've got a canvas animation (obviously not using Velocity) that I've capped at 30fps simply because it's got to use the disgustingly slow context.getImageData() - without any way to detect if we're on battery use we've got to keep things sane ;-)

**Comment by weepy** [comment]
I have animations that I need to run on a very low power device. 30fps
looks good but 60fps looks bad bc of jitter.

**Comment by ydaniv** [comment]
@julianshapiro it's a common practice to throttle FPS rate on slow devices, or of if you have too much logic in the background, since choppiness is mostly caused by unsteady rate, rather then a slower rate.
So it's best to resort to a steady 30 FPS than to try maintaining unsuccessfully an unsteady 60 FPS.

**Comment by PaulBGD** [comment]
30fps is choppy, especially when compared to 60fps.

**Comment by ydaniv** [comment]
@PaulBGD are you aware that cinema films are 24fps?

**Comment by MattyBalaam** [comment]
It can also be a style choice to use a slower frame rate for animation.

**Comment by weepy** [comment]
I would say 30fps is not as smooth as 60fps but it's not "choppy".  Choppy
implies a time varying framerate. Which you get if you try to do 60fps but
your device can't keep up.

**Comment by PaulBGD** [comment]
@ydaniv http://imgur.com/gallery/rNahC

**Comment by ydaniv** [comment]
@PaulBGD , see @weepy's answer above.

**Comment by tommiehansen** [comment]
This seems like a good idea since there are circumstances where capping the FPS isn't a bad thing ie suble animations that is mostly for decoration or stuff that runs in loops for a long duration of time.

I recently created a small site where i used Velocity to loop through an array of colors on the body element + had a png with partial transparency that let those color changes shine through (think a sunset where the sunset colors changes over time).

Before cleaning up the code and doing misc optimizations the cpu really spiked hard. With my misc optimizations it's fine and runs good on poor devices as well (mobiles/tablets etc) but running that particular effect at 60 FPS still doesn't make much sense. I would even say that running anything decorative that can't be interacted with often doesn't need 60 FPS.

**Comment by julianshapiro** [comment]
Hmm. K. I'll code this in as a test and try it out for myself before pushing live!

**Comment by weepy** [comment]
Heya  ! Did you manage to try this out ? 

J

**Comment by Rycochet** [comment]
Just want to point out I've recently seen the Chrome developer tools adding an option to throttle css animations - but rather than framerate it effectively adds a multiplier to the duration so you can see things - linking this up with the mock option might be useful for seeing the actual tween values for each frame (even if it's just a note in the docs)

**Comment by Rycochet** [comment]
The plan is to allow controlling the effective framerate on all animations separately (as well as a global value). This is be related to being able to set the current time within a running animation.

**Comment by alexdor** [comment]
Global fps limit has been added with #818 .

**Comment by pachiraDIG** [comment]
@alexdor @Rycochet Any chance to have this feature added into a 1.5.3 release? : )
