### ISSUE TITLE
Subpixel / rounding option

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#431]
Just remembered this issue - http://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/ (search for "Pixel snapping").

Hence a suggestion for an option ```subpixel:true``` (the default), where nothing is changed at all.

When set to ```subpixel:false``` any translateX or translateY tweens are automatically clamped via Math.round() to make sure that the GPU draws on pixel borders and there's no "dubstep effect" :-P

Not sure how often it'd be used, but I've got at least one project that would look better with it (even if only to us OCD types lol).

**Comment by MattyBalaam** [comment]
I made a codepen illustrating this issue. In particular Firefox has some issues: http://codepen.io/MattyBalaam/details/eaJto/

**Comment by julianshapiro** [comment]
thanks to matty's helpful pen, i see that it is indeed just an issue on ff. since ff on a shockingly steady path toward obscurity, i don't particularly care to code in a feature just for it.

having said this, if you can show me this issue occurring outside of the matty's ff example, @Rycochet, i'd love to see it and would absolutely consider implementing this at that time.

**Comment by julianshapiro** [comment]
i really would love an example pen, etc. curious about this. feel free to keep chatting in here, will read
