### ISSUE TITLE
Velocity is adding unwanted px to value on svg filter.

### ISSUE THREAD

**Issue by MattyBalaam** [julianshapiro/velocity#471]
I am attempting to animate elements of an SVG filter, in this case the x attribute of fePointLight.

Velocity is changing the value in the DOM, but is also adding 'px' to the value, which is invalid in this context.

http://codepen.io/MattyBalaam/pen/ZYqBqe

**Comment by Rycochet** [comment]
Velocity adds "px" to any attributes that it doesn't know uses other things - ie, the hard-coded list of angles and blanks (like opacity etc). In order to be unit-less this would need to be added to that list.

However...

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight

Apparently this one allows multiple values, so it's not ideal for animating to start with - hence I'd suggest making use of tween and rolling your own attribute setting :-)

**Comment by MattyBalaam** [comment]
Thanks for the help, I will try that approach. As it stands, Firefox, Chrome and IE all complain if the attribute is not unitless.

**Comment by Rycochet** [comment]
Can't easily do anything in v1, but in v2 it specifically only adds the unit to certain style properties, and never to an SVG.
