### ISSUE TITLE
Fade in / out having side-effects compared to jQuery's

### ISSUE THREAD

**Issue by sirtawast** [julianshapiro/velocity#496]
Hello, 

I'm having issues with using 'fadeIn', 'fadeOut' shorthands. Also repeatable by scripting the same functionality (mocking the fade shorthands using display and other options).

Here's a fiddle. http://jsfiddle.net/agdvxzm6/

Somehow, there's one frame in the animation without any element in place so the swap is not very smooth.

Tested on Mac versions of Chrome 41 and FF 31.

And if this is not a bug, could somebody help me set up smoother animations without the visual glitch?

Thank you for all the hard work and keep it up!

**Comment by MattyBalaam** [comment]
You could try passing in visibility: hidden so that the element is not
removed from the layout:

http://jsfiddle.net/agdvxzm6/3/

On 16 April 2015 at 13:15, Sampo Haavisto <notifications@github.com> wrote:

> Hello,
>
> I'm having issues with using 'fadeIn', 'fadeOut' shorthands. Also
> repeatable by scripting the same functionality (mocking the fade shorthands
> using display and other options).
>
> Here's a fiddle. http://jsfiddle.net/agdvxzm6/
>
> Somehow, there's one frame in the animation without any element in place
> so the swap is not very smooth.
>
> Tested on Mac versions of Chrome 41 and FF 31.
>
> And if this is not a bug, could somebody help me set up smoother
> animations without the visual glitch?
>
> Thank you for all the hard work and keep it up!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julianshapiro/velocity/issues/496>.
>



-- 
Matthew Balaam
____________________
development and design

matthewbalaam.co.uk <http://www.matthewbalaam.co.uk>
@matthewbalaam <https://twitter.com/matthewbalaam>
07730 953486

**Comment by sampohaavisto** [comment]
@MattyBalaam Still has problems  on my browser :disappointed:.

This fiddle works but is an ugly hack. I'm sticking to this kind of solution for now but it's not very readable or handy. http://jsfiddle.net/agdvxzm6/4/

**Comment by ydaniv** [comment]
Sorry @sampohaavisto this is a question for StackOverflow, not a Velocity issue.

Anyhow, try using the `display` option, might help a bit.

**Comment by sampohaavisto** [comment]
@ydaniv I understand. Still, I'm trying to point out that jQuery's methods can't be replaced by velocity shorthands because they don't animate the same way. I remember reading from an older version of Shapiro's docs that the shorthands were made as a jQuery animate 'drop-in' replacement. It is not very clear to me if this is issue is a bug or the way velocity should work and so I thought it would be helpful to report this.

**Comment by ydaniv** [comment]
@sampohaavisto fair enough.

Personally I think there's no point in trying to achieve an exact match, and it's even pointless, considering the mechanism is different. IMHO the goal should be getting good effects.

But I'll leave it for @julianshapiro to decide whether it requires any change.

**Comment by sampohaavisto** [comment]
:+1:

**Comment by Rycochet** [comment]
Looking into this, and what's happening is that on the frame that complete is called a new animation is started - which starts to actually play on the next animation frame - meaning there will be a single frame between the two running.

Thinking we should see if we're in our current animation frame and the `complete` / `finish` / etc callbacks could start the next frame immediately.

It would be a minor version breaking change (assuming we can figure out where to put it in)...

**Comment by Rycochet** [comment]
All ui-pack animations have been updated to the new sequences code
