### ISSUE TITLE
how to animate background size?

### ISSUE THREAD

**Issue by Pentaxeros** [julianshapiro/velocity#503]
Hi, I want to know if it is possible to include Velocity, to animate the "background-size"

Thanks!

**Comment by kapilgarg1996** [comment]
@Pentaxeros yes definitely it is possible. background-size is just a css property and it can be animated like other properties.
Here is the working fiddle : http://jsfiddle.net/kapilgarg1996/2QetT/9/
Hope it helps.

**Comment by julianshapiro** [comment]
thanks @kapilgarg1996 :)

**Comment by vmadman** [comment]
.. hmm .. but, background-size is not _necessarily_ a single value property.

----

**from: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size**
```
/* Keywords syntax */
background-size: cover;
background-size: contain;

/* One-value syntax */
/* the width of the image (height set to 'auto') */
background-size: 50%;
background-size: 3em;
background-size: 12px;
background-size: auto;

/* Two-value syntax */
/* first value: width of the image, second value: height */
background-size: 50% auto;
background-size: 3em 25%;
background-size: auto 6px;
background-size: auto auto;

/* Multiple backgrounds values by background-image */
/* Do not confuse this with background-size: auto auto */
background-size: auto, auto;
background-size: 50%, 25%, 25%;
background-size: 6px, auto, contain;

background-size: inherit;
```

----

I've been trying to animate my base css of `background-size: auto 3000px;` to `background-size: auto 1000px;` .. but I do not think velocity offers a way to do this.

**Comment by ibrierley** [comment]
Could you use progess and tween to do this ?

**Comment by vmadman** [comment]
I am not sure, I am not familiar with those things.  My solution for this was to just avoid using the `background-size` property.  Instead, I created a new DIV with `position: absolute` and `z-index: -1`.  I then just placed the image using an `IMG` tag and repositioned it.

There are surely other ways to do it, I'm sure, but I chose this one because I am also using `Preload.js` which likes to produce `IMG` tags... so... that was that.

My solution seems to work but I have not tested on more than a few browsers and phones so far, time will tell how well it holds up.
