### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by MoeSippi** [julianshapiro/velocity#527]
TypeError: $(...).velocity is not a function
Did many workarounds and still getting this error.
I'm currently using AngularJS and I put script tags for velocity and velocity angular ui and it's still giving me this error..

**Comment by ydaniv** [comment]
Sorry, not a velocity issue.

**Comment by katrotz** [comment]
Bumped into the same issue. I think it has smth. to do with dynamically added templates. No solution though.

**Comment by katrotz** [comment]
The solutions is as follows: 
jQuery should be executed prior AngularJS, otherwise Angular will initialize its directive elements using jqLite and velocity will not be available. 

As a workaround you will have to reinitialize the elements in your directive `element = $(element[0]);` if you can not control the load order.

**Comment by jakelodwick** [comment]
I encountered this problem (`$(...).velocity is not a function`) using Velocity with RequireJS.

The solution was in [the docs](http://julian.com/research/velocity/) under "Basics: Dependencies":
![image](https://cloud.githubusercontent.com/assets/25925/11486266/01e3bf1a-9786-11e5-9b83-8b7e4d2f2e7b.png)
