### ISSUE TITLE
mobileHA and translateZ: 0 are not enough sometimes

### ISSUE THREAD

**Issue by thehappycoder** [julianshapiro/velocity#534]
velocity docs say that on mobile devices HA is already enabled and also suggest to pass translateZ: 0 to force HA

I did all this but it didn't help my problem when heavy loaded div animated using velocity and translateX lagged heavily on Android phone. Iphone 6 was fine though.

I was able to fix this like this (apply translate3d and then after a while call velocity to do its job):
```
      # Smoothen animation on android (timeout is also required)
      center.css('transform', 'translate3d(0, 0, 0)')
      setTimeout ->
        center.velocity {translateX: '241px', translateZ: 0}, 300
      , 50
```

I hope this post will be useful for somebody.

Alternative way:
Add transform: translateZ(0) to your CSS file directly. But this didn't work for me because after that my center element would blur text and do all sorts of craziness while scrolling.

**Comment by Rycochet** [comment]
The mobileHA option *is* ```transform:translateZ(0)``` - it pushes the rendering onto the GPU, which often means that the "nice" look is lost while it's animating (font smoothing, image resolution etc) - not a problem for animations, but a problem for static displays.

I'd suggest you read up on how hardware acceleration works - and then start looking at how different devices behave and their limits. If it's lagging on one device and not another then my initial thought is that you're trying to push too much into the GPU (such as deep nesting or a large number of elements).

Anyway, your issue is usage and not bug - so head over to https://stackoverflow.com/questions/tagged/velocity.js and ask on there.

**Comment by thehappycoder** [comment]
I think it's a bug because the docs claim the following:
```
Option: mobileHA
mobileHA stands for mobile hardware acceleration. When set to true — its default value — Velocity animations are automatically hardware accelerated on mobile devices.
```

But my experience shows that mobileHA doesn't always work.

**Comment by ydaniv** [comment]
Perhaps the docs are outdated or misleading, but in current version `mobileHA` stands for `translate3d`, see for yourself: https://github.com/julianshapiro/velocity/blob/master/velocity.js#L3541.

**Comment by ydaniv** [comment]
@thehappycoder:
1. Which version of Velocity are you running?
2. Which version of Android you  running on?
3. Which browser you're running this animation in?

**Comment by thehappycoder** [comment]
1. velocity 1.2.2
2. Android 4.2.1
3. Chrome 42

The animation is on sidebar at happycoders.xf.ee (works fine with the hack I mentioned)
It appears when device orientation is vertical

**Comment by Rycochet** [comment]
I'd sat this sounds like more of a workaround for a browser bug - part of the reason the new "will-change" css value was created (which naturally won't help old browsers lol) - hopefully it's of use for others too :-)

**Comment by ydaniv** [comment]
@thehappycoder could you paste here the entire user agent on that phone in Chrome?

**Comment by thehappycoder** [comment]
Mozilla/5.0 (Linux; Android 4.2.1; PAP7600DUO Build/JOP40D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.108 Mobile Safari/537.36

**Comment by Rycochet** [comment]
Closing as a browser issue on a 4-year old browser
