### ISSUE TITLE
Bug in scale forcefeeding when animating together with other transforms

### ISSUE THREAD

**Issue by marian-r** [julianshapiro/velocity#543]
I encounter a bug when I want to animate some transforms, i.e. `translateX` and preserve `scale`:

``` js
$("div").velocity({
    translateX: 100,
    scaleX: [0.5, 0.5],
    scaleY: [0.5, 0.5]
});
```

This causes element to 'blink' at the beginning to `scale(1)`.
See full example: http://jsfiddle.net/65xCP/127/.

**Comment by ydaniv** [comment]
Yep, a bit annoying.
@julianshapiro needs checking out.

**Comment by raphaelrauwolf** [comment]
I am not sure if it matters, but I pre-set the hooks for transform settings, to make sure it doesn't glitch. It might be nice to have a plugin that iterates over all the elements that will get animated and set hooks for transforms etc.

```javascript

$.Velocity.hook($("div"), "scaleX", .5);
$.Velocity.hook($("div"), "scaleY", .5);

$("div").velocity({
    translateX: 100,
    scaleX: [0.5, 0.5],
    scaleY: [0.5, 0.5]
});
```

**Comment by marian-r** [comment]
Thanks for this workaround, I've used it. However, I still think it is a bug and it should work without using a hook.

**Comment by albertogasparin** [comment]
I think I run into a similar issue: an external script sets the `translate3d` property on an element. Then, Velocity kicks in and the animation is:
```js
Velocity(element, { translateY: ['100%', y], translateZ: 0 }, { easing: [100, 20] });
```
I am force-feeding the current translation value, however I can see from time to time a flickering (Chrome desktop and mobile).
Looking at the element props, I can see that Velocity changes `translate3d(0, y ,0)` to `translate3d(0, 0 ,0) translateY(y)`. Don't know if that could be the root cause.

By adding `mobileHA: false`, removing `translateZ ` and making the external script setting `translate(0, y)` then Velocity behaves correctly.

**Comment by ydaniv** [comment]
@albertogasparin that's not a bug, that's by design. `mobileHA` sets `translate3d(0,0,0)`.
Removed the `translateZ(0)`, it's redundant.

If you're animating from different `y` positions each time and the HA hack is reseting to 0 then that's an issue worth checking out, which you should open in a separate thread.

**Comment by jjalonso** [comment]
I have this flickering with scale 1 few milliseconds, even if I set mobileHA to false, on my case im only anmating scale property, but maybe is because in i change the width-height using js before the anim or because started already on 0.075 on css.

**Comment by nikparo** [comment]
This seems to happen if you are forcefeeding the exact same start value as the end value. The very first frame of animation the value will default to 0 rather than the forcefed value.

`translateX: [100, 100]` flickers, `translateX: [200, 200.1]` does not.

Here's a demonstration. (check the console for details)
https://jsfiddle.net/nik10110/nc8tqLLj/

**Comment by Rycochet** [comment]
@nikparo Ugh, nice catch and nasty bug - I've not looked at that code as it's not really needed any more, but think there are a couple of issues all inside it :-/

**Comment by Pointy** [comment]
@nikparo it also happens when you forcefeed *different* values, as in

    scaleX: [1, 0], scaleY: [1, 0], rotateZ("720deg", "0deg")

On the first "progess" call, the `transform` style of the affected element is just `rotateZ(0deg)`, no mention of `scaleX` or `scaleY`.

https://jsfiddle.net/jkz2c54j/10/

**Comment by Pointy** [comment]
I *think* this is caused by the incorrect initialization of the flag called `firstTick` in the tick handler. It's currently (line 4220 of velocity.js):

        firstTick = !!timeStart,

which is of course the *opposite* of the first tick.  If that's changed to

         firstTick = !timeStart,

then the `transform` style is correctly initialized with the force-fed starting values.

**Comment by Rycochet** [comment]
Hopefully #827 will fix this - but `transform` is handled pretty badly in v1 - crossing fingers that they're related.
