### ISSUE TITLE
Add UMD support for patching into jQuery / Zepto etc

### ISSUE THREAD

**Issue by JSteunou** [julianshapiro/velocity#579]
Please, using this library with modern builder like webpack or jspm or browserify or [add your favorite] is really painful because of the lack of AMD / CJS support.

**Comment by ydaniv** [comment]
?!? are you sure you're on the right repo?

**Comment by JSteunou** [comment]
Yes I'm sure. Ho I know you will tell me you already add UMD support. But it's not a correct implementation as you're still loading jquery or zepto from **global window** and not *trying* to require them, catch error then fallback on shim.

No, you shim first, (always when on CJS or AMD because the shim itself is not UMD) then load velocity with this incorrect UMD implementation.

**Comment by Rycochet** [comment]
Added a long time ago, and the last change to the AMD support was back in January - https://github.com/julianshapiro/velocity/blame/master/velocity.js#L409

**Comment by JSteunou** [comment]
You could at least use a try catch for CJS. In case my explanation above was confusing.

```
var $;
try {
  $ = require('jquery');
} catch (e) {
  try {
    $ = require('zepto');
  } catch(e) {
    $ = invokeShim();
  }
}
```

I dont know if this is in the CJS spec but I know some builder consider try catch around require as optional dep.

**Comment by ydaniv** [comment]
And your motivation for this?

**Comment by JSteunou** [comment]
I'm directly concern because I'm using velocity through npm with webpack as a builder. I spent hours tweaking old libraries to make them CJS compatible. This one is on github so I opened an issue about it, because I might not be the only one concerned.

JS is moving fast, and today people are using webpack, jspm or browerify with babel as transpiler so making libraries not using global variables and AMD / CJS compatible became a minimum.

**Comment by ydaniv** [comment]
Have you tried searching the issues and open PR's for related issues?

**Comment by JSteunou** [comment]
You mean like #578 or #576 or #490

**Comment by ydaniv** [comment]
(:

**Comment by kenwheeler** [comment]
Hey guys, allow me to introduce myself. I took stewardship over this project yesterday. My first order of business is to convert the project to a modern build stack. I'm going to convert to CommonJS/ES6 and modules, a webpack based build system and have linting and test tasks built in. This will make this easier to use in common JS environments, and will let you require and utilize submodules as well as a full UMD build. The exposed build system will also make it easier to edit and create pull requests. So stay tuned.

**Comment by JSteunou** [comment]
Could not hope for more. Cannot wait to see a new release @kenwheeler

**Comment by paulfalgout** [comment]
@kenwheeler Fantastic

**Comment by JSteunou** [comment]
:wave: @paulfalgout

**Comment by petermakowski** [comment]
@kenwheeler fantastic news!

**Comment by Rycochet** [comment]
Just had a thought - would it be possible to remove the jQuery shim code entire, and have jQuery as a git submodule, then use grunt to build a custom jQuery version as the new shim instead (rather than having custom code that does the same thing, this would use the jQuery code directly). https://github.com/jquery/jquery#modules

Note that this is just a thought that I'm putting down here for once things are split out and we can see the cost/benefit to it :-)

As a side note, jQuery.offset() / .width() etc shouldn't be used for sizes etc as it doesn't take any notice of transform - so that needs to be cleaned out and el.getBoundingClientRect() needs to be used instead.

**Comment by lddubeau** [comment]
I agree with @JSteunou that the UMD support needs rethinking. 

As it stands right now, it is impossible to guarantee that Velocity will see jQuery when it is loaded by RequireJS *unless* one resorts to ugly fixes. Velocity's documentation mentions using `shim` in the RequireJS documentation but this is in fact wrong, as `shim` should be used only with non-AMD modules (that is, modules that do not call `define` to register themselves with the AMD loader), but Velocity does call `define`. Quite simply, RequireJS does not define any semantics to the use of `shim` with actual AMD modules. In cases when someone has merely used the suggested `shim` in their RequireJS configuration and  works, it is just luck. (Yes, really, it is just luck. It may be *repeatable* luck, but luck nonetheless. I can give a fuller explanation if needed.) The only reliable way I'm seeing to load Velocity 1.2.3 so that it definitely can use jQuery, with a stock RequireJS installation (no plugins), would be to wrap all entry points of an application with an ugly fix like this:

```
require(["jquery"], function () {
    require(["myapp"]);
});
```

This ensures that jQuery will load before anything else, including Velocity. There's no amount of fiddling with RequireJS' configuration that can do the same, given the way Velocity calls `define`.

----

It would make sense to split off the jQuery shim that Velocity currently incorporates into its main file. Doing so would allow users to configure Velocity to work with or without jQuery. Velocity could call `define` like this:

```
    } else if (typeof define === "function" && define.amd) {
        define(['jquery'], factory);
    /* Browser globals. */
    } else {
```

and the code of `factory` would have to be adapted to the new usage. In particular, it would take its reference to jQuery from the parameter passed to it instead of looking for it in the global space. If someone wants to use Velocity with jQuery, they would not have to do anything with their RequireJS configuration other than make sure jQuery is available to RequireJS and loadable under the name `jquery`. If they want to use the shim instead, then assuming the jQuery shim is in a file named `velocity.jquery.shim.js`, they could do:

````
require.config({
    paths: {
        jquery: "path/to/jquery",
        velocity: "path/to/velocity"
    },   
    map: {
        velocity: {
            jquery: 'path/to/velocity.jquery.shim'
        }
    }
});
```

This tells RequireJS that when `velocity` requires `jquery`, RequireJS should load `path/to/velocity.jquery.shim` and return the value of this module instead of the value of the `jquery` module. (It would be possible to reduce the name of the shim file to `velocity.jquery.shim` in the `map` config *if* a `paths` entry is created for it to map the shorter name to the full path, but since this is a one-time deal and won't be explicitly used anywhere else, there's little to gain from adding a `paths` entry to shorten the `map`.)

**Comment by Rycochet** [comment]
The latter part of the idea of defining "jquery" might actually cause far more problems due to the way that requirejs works as it scans the source for specific regex strings to recognise what is provided and supplied - especially when using r.js to build a static file.

Forcing people to do anything to their requirejs config just to support Velocity is pretty bad - far better is simply to provide two versions of Velocity, one in a "`no-jquery/`" subfolder (or vica-versa), that are otherwise named the same, and easily available immediately on all the CDNs, so only the path needs to change depending which one is wanted (as opposed to putting the shim requirement in the filename which means having to do something to the requirejs config again).

**Comment by lddubeau** [comment]
@Rycochet If you found a case where `r.js` is confused by a `map`, then please [file an issue](https://github.com/jrburke/r.js/issues) because that would be a bug. I've used many `map` configurations without ever running into any problem.

I'm not a fan of the multiple-builds solution, but if the maintainer(s) decided on having multiple builds, it would make sense to set the "using jQuery" build as I explaned above so that:

1. Velocity would behave like a proper AMD module. Grabbing jQuery from the global space is not okay for an AMD-module.

2. Developers could use something else than jQuery if they wanted to (e.g. Zepto), provided that the substitute offers the minimum amount of functionality that Velocity wants. It is not reasonable to expect that the maintainers of Velocity will offer builds for every jQuery substitute under the sun, and as a user of Velocity, I'd much rather have to use a `map` in my RequireJS configuration rather than have to build Velocity to use a substitute.

**Comment by amenadiel** [comment]
My two cents:  the shim and the library shouldn't be in the same file, for starters. It's an unnecesary coupling.

The main library should have an UMD wrapping either to export:

`module.exports = factory(require('jquery'));`

Or define

 `define(['jquery'], factory);`

That's all. Look at Backbone. People have been replacing jQuery with Zepto and underscore with lodash. You just need to get along with the fact that you're dealing with named modules, and overriding them needs some config.

**Comment by JSteunou** [comment]
No shame plug because this project is very dead: https://github.com/bendc/animateplus no dependencies, ultra light compared to velocity, modern, written in es6.

**Comment by davidspiess** [comment]
The shim should be standalone and not fallback to jQuery though it's available in the global namespace. At the moment it breaks if the used jQuery version is less than 1.4

**Comment by Rycochet** [comment]
When wanting to patch any other library that isn't directly supported and available before Velocity (such as via RequireJS or something other than jQuery or Zepto) then see the [Velocity.patch()](https://github.com/julianshapiro/velocity/wiki/Advanced---Patch) method.
