### ISSUE TITLE
Ajax "async=false" + "Sequence"

### ISSUE THREAD

**Issue by asmadi** [julianshapiro/velocity#588]
I'm trying to run a sequence by using "$.Velocity.RunSequence(seq);" and after this there is an ajax call with "async=false" , So the problem is the sequence won't run until the ajax response is back But if i change the async to "async=true" the sequence works just fine!! So please is there anyway to get this to work? Because i've looked everywhere including the book and no one mentioned it !

Thank you in advance!

**Comment by Rycochet** [comment]
That's how Javascript works - by using ```async=false``` you're basically saying "stop anything else at all from happening until this returns" - if you're trying to use a little loading animation then either change things so you're not blocking all Javascript calls, or change it to a CSS Animation which won't be blocked.

**Comment by asmadi** [comment]
You are totally true, But maybe i didn't sent the right massage, the thing is i add the sequence before any ajax calls then after the animation start the ajax call should start so is there anything i can get benefit from like on start / complete something that will stop the ajax call until the sequence start?

**Comment by Rycochet** [comment]
It makes no difference, Velocity is Javascript, an async AJAX call blocks *all* Javascript - the animation itself takes place in requestAnimationFrame callbacks (ie, after whatever code you're running has returned control to the browser) - so even by having the AJAX call after the Velocity call won't make any difference as the actual animation will be blocked.

This isn't any form of bug, so should be on StackOverflow rather than the Issue tracker - a quick search on there finds this - https://stackoverflow.com/questions/6548507/javascript-async-and-synchronous-ajax-ops from back in 2011

**Comment by asmadi** [comment]
Got your point and thanks for your cooperation.
