### ISSUE TITLE
Callout setInterval animation stack up when you move to next tab and back

### ISSUE THREAD

**Issue by jelenajjo** [julianshapiro/velocity#592]
Here is the callout function [codepen example](http://codepen.io/julianshapiro/pen/Fybjq) and you can see that `div` is shaking repeatedly with some delay. But if you now go to some other tab, stay there for a while and go back to this example, you will see that it animates the `div` repeatedly without delay, and then goes back to normal. I created [short video](http://screencast.com/t/cw7Efliy) to show you so you don't bother with tabs.

It looks like it piled up the animations while you were away and then started them and after finishing with piled up ones, it starts animating normal again.

**Comment by Rycochet** [comment]
Running animations handle the tab being hidden properly, the problem is that you're trying to create new ones while it's not visible. As a workaround I wrap things like that in a ```if (!document.hidden) { ... }``` to make sure it doesn't queue up.

Not sure what Velocity should do when an animation is *added* when it's hidden - but to my mind it should work the same as when the animation already exists, and silently run through it - looks almost like "when there's no running animations we're going to push the first frame into rAF instead of setTimeout" - anyone who knows that code want to have a look?

**Comment by Rycochet** [comment]
Using setInterval to add multiple animations is not a good way to do it - you need to check if a window is in the background (`document.hidden`) and not add them when this is true.
