### ISSUE TITLE
Can Meteor package be upgraded to 1.2.3?

### ISSUE THREAD

**Issue by mitar** [julianshapiro/velocity#597]
It is still 1.2.1.

https://atmospherejs.com/velocityjs/velocityjs

**Comment by derwaldgeist** [comment]
+1

It would also be awesome if you could fix the Atmosphere Github link to directly point to the repo for the Meteor package. I was trying to figure out if UI was already included, but can't tell since the Github link points to the core velocity Github repo.

**Comment by danielkalen** [comment]
+1

**Comment by danielkalen** [comment]
Seems like it's been 20 days since you opened this issue and Julian still didn't update the Meteor package :(
As a temporary solution I've uploaded the 1.2.3 version which is called danielkalen:velocityjs.

**Comment by kenwheeler** [comment]
@danielkalen I'm the steward of this repo now. How does the meteor version work? I can get it pushed out soon if I know how to do it.

**Comment by kenwheeler** [comment]
I've typically only used bower and npm

**Comment by mitar** [comment]
The links points to this?

But now looking at the content of this repository it is already `1.2.3`. So I am not sure if this package is really what is available under `velocityjs:velocityjs`.

**Comment by danielkalen** [comment]
@mitar Here's proof that the current package located on atmospherejs is 1.2.1 http://share.danielkalen.com/2wM/

**Comment by danielkalen** [comment]
@kenwheeler You have to download meteor (obviously), and create a package possible using this tutorial: http://www.webtempest.com/meteor-js-packages-tutorial

Basically you need to create the package dir and inside have a package.js (http://docs.meteor.com/#/full/packagejs) describing the behavior of the package, along with the latest version (I think minified) of velocity.

**Comment by alejandroiglesias** [comment]
Any updates on this? It has been a year since opened and we're still having access to Velocity 1.2.1 from Meteor packages.

**Comment by Rycochet** [comment]
I've not had the time to look at it - beyond seeing that the tutorial link is dead - the atmospherejs link is saying 1.3.2 but I'm assuming it's grabbing the readme and not the js files?

If someone wants to put together a Pull Request to add the needed things then it would be helpful :-)

**Comment by abernix** [comment]
@Rycochet I'm not familiar with VelocityJS but thought I'd chime on on this and try to help as it was mentioned in a Meteor issue (linked above).  As you said, the README is just getting updated from the GitHub README, but the package itself has been stagnant on 1.2.1 since it was initially released.

Ultimately, I'm fairly sure this package isn't critical anymore as Meteor natively supports NPM modules.  Though there do seem to be a decent number of legacy users using this Meteor package and Meteor packages are still actively maintained by many, so it's up to you if you want to proceed.  I certainly **think** it can be deprecated in favor of the pure NPM version, but again I'm not familiar with this package.

The process for creating a Meteor package is relatively simple and documented in this official guide: https://guide.meteor.com/writing-atmosphere-packages.html.  You would need to install Meteor.  It's not difficult, but perhaps a user who is more familiar with the process might more able to help you with it quickly... it appears that @chrismbeckett had originally published the package on Atmosphere, but I'm not sure if they're still involved.

At first glance, it would appear that the Meteor package has never been checked into Git so you may be missing the package source for it which shows how it was laid out.   I've gone ahead and [attached it here](https://github.com/julianshapiro/velocity/files/621709/velocityjs.velocityjs.zip) in case it's helpful to anyone.

In your case, the package is already created so you'll just want to bump the versions, reference the most recent versions of the JS and then run `meteor publish` from that directory.  You would need the credentials for the `velocityjs` org though.  Also, I would recommend running it from a sub-directory of the repo and not the top level to avoid bundling unnecessary dependencies (see moment/moment#3531).

Anyhow, those are my two cents. :)

**Comment by alejandroiglesias** [comment]
Seems best to use the npm version since it's preferred now over Meteor packages.

**Comment by Rycochet** [comment]
@abernix That's really useful, thanks :-)

I'd like to get the Meteor package set to depreciated if possible then - so it uses the NPM package instead - will need to find out who controls the `velocityjs` organisation first (I'll email around, but people are on holiday right now) - hopefully this issue can be laid to rest soon :-)

**Comment by mitar** [comment]
I think velocity is autopublished: https://github.com/MeteorCommunity/discussions/issues/14#issuecomment-237774586

The issue is that since MDG discontinued meteor.com free hosting, autopublishing does not work anymore.
