### ISSUE TITLE
how to get final animation value

### ISSUE THREAD

**Issue by heaversm** [julianshapiro/velocity#599]
Hi - I am looping through a fairly large number of svg circles and applying translateX to them to move them to random positions within a certain range of their original position :

```
var newX = curX + randomNumber(-moveDist,moveDist);
$circle.velocity({
      translateX: newX
    },{
      duration: animTime,
      complete: onCircleComplete,
      delay: delayTime
    });
```

When they reach the position, I would like to move them again in the same manner, however it is a bit difficult to get the new translateX position (have to do something like get the transform property and run a regex to find the "translateX" component value.

```
var onCircleComplete = function(){
    var style = $(this).attr('style');
    var transXRegex = /\.*translateX\((.*)px\)/i;
    var xTrans = transXRegex.exec(style)[1];
  }
```

Is there an easier way to get this from the "complete" function or something?

**Comment by Rycochet** [comment]
Not a bug report so should be on StackOverflow.

The ```complete``` function (http://julian.com/research/velocity/#beginAndComplete) is only called once per animation rather than per element, so wouldn't be of any use for getting the values - the ```progress``` function will pass the values however so you could cache those instead - but I don't know if it is guaranteed to be called for the finishing frame - your parsing option is the most obvious and easiest way to do it (though could be made slightly safer and shorter).

**Comment by heaversm** [comment]
ok thanks
