### ISSUE TITLE
"finish" calls complete event asynchronously

### ISSUE THREAD

**Issue by tsschaffert** [julianshapiro/velocity#606]
I tried to port an animation from jQuery.animate to velocity. Before a new animation starts, I cancel all previous animations on this element by calling stop(). I want to execute the complete-Events of the animations, so I use "finish" in velocity. 

My problem: With jQuery, the complete event was executed directly, blocking code execution until it was finished, so after calling stop, I can continue with the rest of my logic.
In velocity, the complete event seems to be executed asynchronously, which breaks my current code.

A really basic example:
http://jsfiddle.net/ns46xp1u/1/
I expected the alerts to be in order, but the complete event is executed as the last instruction.

**Comment by Rycochet** [comment]
As "finish" changes values I believe that it waits for the next animation frame to actually do it - I'd call this an unintentional bug as it's something that you'd expect to complete immediately - so either the docs need updating to make this clear, or some changes in the internals need to be done - the potential display issue of not using rAF for updating isn't as important as completing when expected imho :-)

**Comment by authcode** [comment]
I was going to open a similar issue when I came across this. I am also struggling with the asynchronous nature of "finish"; it's just a bit counter-intuitive. Take this example: http://jsfiddle.net/65xCP/166/
This scenario is contrived but it demonstrates the problem I was having succinctly. Having called "finish" before "stop" I would expect the "complete" callback to fire, but it doesn't since "stop" is seemingly executed first and prevents "finish" from doing anything.

**Comment by Rycochet** [comment]
All callbacks in V2 are async - so even though the animation itself may finish immediately with `"stop"`, or at the next frame with `"finish"`, the functions called will be done in the next time JS can handle it directly. If you're not wanting to let them call, then use `anim=Velocity(...); anim.velocity("option", "complete", null); anim.velocity("stop");`
