### ISSUE TITLE
newbie simple question

### ISSUE THREAD

**Issue by brw31415** [julianshapiro/velocity#608]
hi, any help appreciated , simple set up https://jsbin.com/ronigutone/edit?html,css,js,output thanks

**Comment by Rycochet** [comment]
Maybe try asking a question about what the problem is - however if you opened the console you'd see an error - ```Uncaught ReferenceError: $ is not defined``` - which looks like you're trying to use jQuery when you're not including it.

The guidelines you get pointed at when opening the issue clearly state you should be using StackOverflow if it's not for a bug, and this is clearly not a bug...

**Comment by brw31415** [comment]
sorry for the indiscretion, but yea, it works!  that rocks. imho  there's a
little too much discussion in the docs about using versus not using jquery,
css, etc ,when most of us just need to get something up quickly and don't
really care.
