### ISSUE TITLE
Doc error for scroll: scrolling to a jQuery object container does not works

### ISSUE THREAD

**Issue by nitriques** [julianshapiro/velocity#612]
In the docs, it's stated that this should work, but it does not.

``` js
$element.velocity("scroll", { container: $("#container") });
```

This works

``` js
$element.velocity("scroll", { container: "#container" });
```

**Comment by maxfenton** [comment]
I know this is the wrong place to mention it, but I just spent a long time trying to debug an issue where `.velocity("scroll")` didn't work at all and the problem was `body { overflow-x: hidden; }` 

If it's not in the scope of the Velocity docs, sorry to bother, but if you're making the change above and feel like mentioning that issue, it may save someone else a great deal of confusion.

**Comment by Rycochet** [comment]
Scroll has been rewritten in V2
