### ISSUE TITLE
Set the animation to a specific percentage?

### ISSUE THREAD

**Issue by matthewmueller** [julianshapiro/velocity#613]
Apologies in advance because I'm pretty sure I'm missing something, but I can't find anywhere in the documentation where to manually set where you are in the animation. Something like:

``` js
// set the opacity to .5 (when eased linearly)
Velocity(element, { opacity: [0, 1] }, { percentage: 0.5 })
```

Is this possible with velocity?

**Comment by Rycochet** [comment]
I don't think it's possible (nor in jQuery) - the ```progress``` callback has the percentage in it, but that's worked out at the time of the call from the start, end, and current timestamps - if pause #14 ever gets added (yes, the issue got closed, but it's still a good idea) then I think this would make a useful (and workable) addition to it - though more likely would need to be some sort of callback (rather than an option) so you could change it while running (ie, make loop/repeat just change the timestamp rather than having extra cose specifically for them).

**Comment by yckart** [comment]
Yeah, definitely a thing that I'm missing... Could be great improvement for parallaxifying and other user interaction based animations. In jQuery we do this by a simple call to [`Tween#run`](https://github.com/jquery/jquery/blob/6072d150d61655ec07f714e1d58a0bd7baa5ec3f/src/effects/Tween.js#L29-L47) passing in the current `percent` to interpolate the values:

```js
animation.run(progress)
```

**Comment by Rycochet** [comment]
Linked to #314 among other things I think.

**Comment by Rycochet** [comment]
It is now possible to do this in v2 (develop branch). Currently you can start an animation with a negative ```delay``` value to start it at some point later into the tween. Once running you can use the result of that initial call and set the ```startTime``` or ```percentComplete``` option to play with it:

```typescript
var anim = Velocity(elements, properties...);

var percentComplete = anim.velocity("option", "percentComplete");

anim.velocity("option", "percentComplete", 0.5);
```
