### ISSUE TITLE
Velocity removes transformation on SVG components when rendering on mobile devices

### ISSUE THREAD

**Issue by KevinNTH** [julianshapiro/velocity#625]
Hello,

I use Velocity to animate some SVG component, and I found a bug which happens only on mobile devices.

Basically, I have a SVG circle on which I apply a transformation (rotation). Then I apply a animation on it with Velocity, the transformation is removed.

Please take a look at my [codepen](http://codepen.io/KevinNTH/pen/pgNzzq), and use the Chrome dev tools in order to render the pen on mobile device mode (no problem on desktop).

**Comment by Inoir** [comment]
You can see this issue also if you simulate mobile mode on desktop. The problem here is there is no check if there is already an transform for mobile.
In this shown example there is an rotation transform applied from css and velocity added translate3d(0, 0, 0) for HA. So the rotation is gone.
Same happens btw if youve already translateY applied and you want to animate scale or rotation. The initial applied transform get ignored/overwritten.

**Comment by KevinNTH** [comment]
Hi !

Exactly one year after, I want to come back to this issue and tell you what I have found.

The issue was posted here: https://codepen.io/KevinNTH/pen/pgNzzq and is still up to date. On mobile, when the animation starts, the rotate transformation is gone. 

I have test many workarounds in order to get ride of this issue. You can see here: https://codepen.io/KevinNTH/pen/ZBgKdG

I try this:
- use `<g>` tag and use css3 transform property
- set rotate transformation on `<g>` tag
- use a `div` wrapper and use css3 transform property 

These workarounds may help anyone who encounter this issue.

BTW, on iPhone, no matter of these workaround, the rotate transformation **is not applied** on the circle element. It's not related to `velocity` and I think that the browser engine simply ignore rotate transformation on circle... (because basically, rotate a circle does not make sense).

Cheers.
