### ISSUE TITLE
Is the project active?

### ISSUE THREAD

**Issue by marian-r** [julianshapiro/velocity#632]
Hey, I just wanted to know what is the status of this repo @julianshapiro @ydaniv? Is it stil active?

**Comment by kenwheeler** [comment]
Indeed it is. Expect to see a release cut in the next week or so. I've been working on modernizing the build system and getting CI integrated.

**Comment by marian-r** [comment]
Thanks :) I just saw pretty quiet period in the commit log, so I wasn't sure.

**Comment by Rycochet** [comment]
Will be nice to see some activity again - there's a large number of open issues (including a lot that could simply be closed) - and looking forward to having a nicely built project :-)

**Comment by ydaniv** [comment]
@kenwheeler with all due respect and with best intentions, this is an open-source project, and as such, it's expected that development be done in the open. Would be nice if progress could be viewed and tracked in a public branch (:
Transparency is golden.

**Comment by kenwheeler** [comment]
@ydaniv the branch will be up this week or so for review and will be PR'd like anything else. Changes to the actual source are minimal at this point.

**Comment by kenwheeler** [comment]
@Rycochet if you see something that's an easy close can you tag it with a comment so that I can do so?

**Comment by Rycochet** [comment]
Just needs time to go through things - and not had enough of that lately either ;-)

**Comment by kenwheeler** [comment]
@Rycochet heard that

**Comment by kenwheeler** [comment]
While we're here, is there anything in particular that folks would like to see in the next release? This is what I'm shooting for:

__Build System__
Right now, tests aside, the repo is more of a distribution than source. I have the actual source locally, which includes a Gruntfile, and which has not been publicly exposed. I want to change that. I think moving forward, this project will rely heavily on contributors and I want to make it easy for them to contribute. I plan to introduce linting, a test runner, and a proper build process. This way I can get PRs hooked up to Travis and we can be sure that PRs wont break anything

__Docs__
I'd like to open source the docs so that we can accept community contribution to them and clear up any inaccuracies or erroneous syntax

__UMD__
There has been some discussion around how UMD works and the way that the shim is applied. I'm generally of the opinion that the shim should be an explicitly included dependency, rather than implicitly applied as a result of not finding a suitable dom querying lib. Does anyone have any thoughts on this in particular? Also, package.json has jquery as a hard dependency, which to the best of my knowledge, is not necessarily the case.

**Comment by kenwheeler** [comment]
Also @ydaniv can we chat about the approach to issues moving forward? I'd like to change the verbiage on the current CONTRIBUTING.md to actually encourage pull requests, and I'd like to discuss how we handle demo-less issue reports. I'm available as `thekenwheeler` on skype if you have any bandwidth over the next few days.

**Comment by Rycochet** [comment]
The build system will make the biggest difference to things - and as you say it'll make PRs useful - there's a lot of code ideas come through here over time that could have been put in them instead ;-)

Maybe use GitHub pages for docs, and link to the GitHub wiki for specific examples and code (ie, the more common and useful things that have some up on StackOverflow)

I agree that the jQuery shim should be a separate dependency - sadly it's not easy to do an either/or RequireJS request (not without a custom module etc) - so maybe hold back on that till a 2.x release (thinking CDN related here) unless the default file is the shim version until then? Saying that - having the build system choose whether to include the shim should be included would work for local builds - ie, not unlike jQuery does things in it's own build setup.

The biggest improvement will simply be activity starting up again, which will get people putting time and effort into helping :-)

**Comment by kenwheeler** [comment]
Yeah, if I pull the shim out by default, it will absolutely have to get bumped to 2.0.0.

A gh-pages branch will be absolutely essential.

In regards to the library itself, there are contributors here that know way more about Velocity than I do. TBH in the current repo state, I'm not comfortable editing the code. I would feel a lot better making the project even more open, and putting in a system of checks and balances so that we can add features and fix bugs with confidence. Generally speaking, the project is stable for the 99% use case. Moving forward I'd like to focus on fixing the other 1% cases, adding certain features or APIs that will make Velocity work seamlessly in modern javascript projects, and adding a team of contributors who can help shape the project moving forward.

**Comment by sdempsey** [comment]
welp, I've been using velocity on nearly every project for the last 15+ months.   I'd love to help shape it moving forward.  I'll keep an eye on the repo and see where I can jump in.  Really excited to see work happening here again!

**Comment by kenwheeler** [comment]
@sdempsey any suggestion would be super appreciated.

**Comment by thasmo** [comment]
Nice to read something about the project's state. Keep up the good work! :)

**Comment by TechInterMezzo** [comment]
Any news on this matter?

**Comment by Rycochet** [comment]
It's alive!!!!! Muahahahahaha :-)
