### ISSUE TITLE
Easing is gone when on complete - reverse is performed with complete handler

### ISSUE THREAD

**Issue by milosdjakonovic** [julianshapiro/velocity#638]
http://codepen.io/milosdjakonovic/pen/JGZRNL

click to box and see animation
uncomment line 15 and comment line 16
again click to box and see animation

---

Setting even a empty function as complete handler to `$().velocity('reverse')` destroys easing.

**Comment by Rycochet** [comment]
@kenwheeler Actually, it's *anything* in the options (even `{unknown:null}` - but an empty `{}` doesn't cause it - so I'd guess that where it looks at copying the options it's taking defaults rather than the previous set for the reverse...

**Comment by milosdjakonovic** [comment]
@Rycochet yeah, but for now it seems like this bug sets to default only **easing** option, for example animation speed is not affected...

**Comment by Rycochet** [comment]
Looks like this is the offending section - https://github.com/julianshapiro/velocity/blob/master/velocity.js#L2630 - the code reads as if it should do what's needed, but obviously isn't - if I have time I'll figure it out and post, otherwise someone else might be able to figure out what's going wrong (my initial reaction is to check the `$.extend()`).

**Comment by milosdjakonovic** [comment]
Just to confirm that this issue is still there with new version of Velocity.
