### ISSUE TITLE
Lack of animation while page still loading in Firefox

### ISSUE THREAD

**Issue by azharijelek** [julianshapiro/velocity#641]
Hi guys, I just got trouble with firefox.

Normally, the animation is as smooth as in webkit browsers. 

the difference is, webkit browsers still render smooth animation while page still loading. Firefox doesn't.

How do we fix that?

**Comment by Rycochet** [comment]
Short of using css animations I don't think you can - there's only two things that will prevent frames from rendering on time - something blocking Javascript, or something blocking page rendering (it it's still happening but stuttering it's probably Javascript, if it's constantly playing catchup then it's probably rendering) - both of which are out of our control - and only the first one can possibly be fixed with css animations / transition - supplying a JSFiddle might be able to help with suggestions, but this is likely more useful on StackOverflow etc.
