### ISSUE TITLE
Loop property for effects

### ISSUE THREAD

**Issue by VadimZhiltsov** [julianshapiro/velocity#654]
Currently there isn't ability to create effect with looping.
That's because effects have white listed properties and `loop` property is not allowed.
I have tried add it to white list and there is not any issue with it. 
Test effect config:
```
velocityHelpers.registerEffect({
		calls: [
			[{
				rotateZ: '360deg'
			}, 1, {
				easing: 'easeInOutCirc',
				loop: true
			}]
		]
	})
```

So I have created pull request to whitelist loop property.
Here is the pull request https://github.com/julianshapiro/velocity/pull/655

**Comment by Rycochet** [comment]
The downside of this is that it'll probably only loop the last part of a multi-part effect - needs a demo to show, and then we can look into something a bit better - my personal choice would be something more akin to a step-backward style recording to record an array of effects - maybe an option of `record:true` on one step, then a later step would have `loop:true` to jump back to the first - then when it hits that last loop again it goes back to the start - needs thought and planning...

**Comment by VadimZhiltsov** [comment]
@Rycochet I apologize for so long response.

I has added few changes to my pull request and now there is ability to loop all sequence. Here is example:
https://jsfiddle.net/gfmxt60u/

But I left an ability to loop the only step, it could be helpful. Here is another one example:
https://jsfiddle.net/x7f2Lr0d/2/

Also I'm thinking about looping few steps from big sequence. It could have such API:
```
$.Velocity.RegisterEffect(EFFECT_NAME, {
    defaultDuration: 2000,
    calls: [
        [ { top: 100 }, 0.25],
        [ { left: 100 }, 0.25],
        [ { top: 150 }, 0.25 ],
        [ [
                [ { top: 200 }, 0.25 , { loop: true }],
                [ { left: 200 }, 0.25 , { loop: true }],
          ] , 0.25 , { loop: true }]
    ]
});
```
But it could be some tricky.
This is a topic that needs to be thought

**Comment by Rycochet** [comment]
Don't worry about taking time, I'm still waiting for source code so I can start doing stuff ;-)

I like how that is looking - will see how it integrates, especially for tests - but think you've definitely got something worth looking into.

The API idea I also like - being able to group sections could also be a different way to register effects - the "named" effect could just be a shortcut to an array that is otherwise identical - having an array as the first argument instead of an object isn't currently overloaded (so wouldn't break anything), so having it as a simple way to link things together for looping or reversing as a whole might be good - definite thought, and possibly splitting off into it's own issue when things start being updated ;-)

**Comment by VadimZhiltsov** [comment]
@Rycochet I'm sorry for my misunderstanding, but what source codes are you waiting?

In my previous message, I attached few jsfiddles with source code from pull request and  examples of usage. If you need few more, please let me know.

**Comment by Rycochet** [comment]
@VadimZhiltsov I'm now on the VelocityJS team - just that I'm the only one with any time for coding, but the only one without the source - the github version is compiled, so part of the todo list is getting things completely public...

I saw, they did the job perfectly, so just a case of getting things worked out then merging / rewriting things as needed :-)

**Comment by VadimZhiltsov** [comment]
Got it, thank you for explanation :)

**Comment by Rycochet** [comment]
In v2 the way this is handled is changing, as all sequences are now treated as a single propertyMap.
