### ISSUE TITLE
Combine scale animation with keyframe animation?

### ISSUE THREAD

**Issue by john-goldsmith** [julianshapiro/velocity#658]
Is combining a CSS keyframe animation with Velocity `scale` property animations supported?  For example, I'm trying to scale and fade-in (using Velocity) a loader that is rotating infinitely (using CSS keyframes).  The fade-in and keyframes work fine together, but the scaling gets lost.  Conversely, if I remove the keyframes, the fade-in and scaling work fine.  Am I missing something?

```sass
// styles.sass
#loader
  position: absolute
  animation: rotateLoader 3s infinite

@keyframes rotateLoader
  0%
    transform: rotate(0deg)
  25%
    transform: rotate(90deg)
  50%
    transform: rotate(180deg)
  75%
    transform: rotate(270deg)
  100%
    transform: rotate(360deg)
```

```js
//script.js
import Velocity from 'velocity-animate';
function showLoader() {
  let loader = document.querySelector('#loader');
  return Velocity(loader, {opacity: [1, 0], scale: [1, 0.5]}, {duration: 1000}); // opacity works, scale doesn't
}
```

Thanks!

**Comment by Rycochet** [comment]
Both scale and rotate use the same `transform` property - the only way to get them working together **on the same element** is to have a single place doing them (either css or Velocity).

I added the emphasis as you can nest the rotate inside another element that gets the scale - which will then work with the two techniques due to the `transform` properties being set on separate elements ;-)

**Comment by john-goldsmith** [comment]
Brilliant, thank you!
