### ISSUE TITLE
Delayed Animations/Overlapping

### ISSUE THREAD

**Issue by futr3** [julianshapiro/velocity#669]
Hello, thank you for this great library Julian.  It has been great fun to work with.  I am currently facing an issue with timing and I'm not sure what I may be doing wrong.

I have setup a Hero image at the top of the page with some animation text for the description of the clients business - simple fade in and fade out with a delay.  For some reason if it starts loading while the page is out of view - my " opacity: '0' " stops working for my fade outs and I get tons of overlapping (everything).  Any suggestions? 

Link:
http://www.565media.com

It doesn't always happen, but the client is complaining.  The only way I have found to recreate it is by loading the page and then leaving the tab while the animation loads.  When I select that tab again, the animation sticks, the opacity timeline changes etc.

Thanks for your time!

**Comment by Rycochet** [comment]
Can you put the relevant piece of code into a fiddle so we can actually see what's being used - https://github.com/julianshapiro/velocity/blob/master/CONTRIBUTING.md

**Comment by futr3** [comment]
Yes, thank you for the link.  Apologies for not reading it first.

http://jsfiddle.net/futr3/qa4radae/

**Comment by Rycochet** [comment]
Had a look at this (sorry for the delay), and the problem seems to be the size of the image you use - it's almost 8mb - and that's hitting the connection to the server, with the limit on number of connections it's most likely that the css is getting delayed and stopping things from displaying properly.

Reduce the resolution of the image, and then run it through something like https://tinyjpg.com/ - anything over 200k is probably overkill...
