### ISSUE TITLE
Velocity typescript definitions 

### ISSUE THREAD

**Issue by bassamseif** [julianshapiro/velocity#670]
I have tried looking for type definitions for velocity the only one i could find is on tsd `tsd install velocity-animate' but does not support velocity using Zepto. 
Any ideas ?

**Comment by Rycochet** [comment]
I think you'd need to add several type alias lines simply because although Zepto is meant to be compatible, the definition file names things totally differently.

Personally I've got a split project that uses Zepto and jQuery depending where it's getting used, and I simply use the jQuery definitions and ignore the Zepto ones.

**Comment by bassamseif** [comment]
cool thanks
