### ISSUE TITLE
Test case to show choppiness resulting from not using RAF timestamp

### ISSUE THREAD

**Issue by joliss** [julianshapiro/velocity#684]
Velocity uses `(new Date).getTime()` instead of the RAF `timestamp` argument ([velocity.js:3366](https://github.com/julianshapiro/velocity/blob/9c9c052a5fb6d5854c9aad931d9410c6790816ee/velocity.js#L3366-L3368)):

``` js
/* We ignore RAF's high resolution timestamp since it can be significantly offset
   when the browser is
   under high stress; we opt for choppiness over allowing the browser to drop huge
   chunks of frames. */
var timeCurrent = (new Date).getTime();
```

I created a test case to demonstrate the resulting choppiness: http://codepen.io/joliss/pen/rLOxBb

My hope is that you can use this test case as a debugging aid, and as a motivating example to convince browser vendors to get the `timestamp` offset issues resolved.

Running the CodePen, we see that there is some slight choppiness with the default `getTime` implementation:

![a pen by jo liss bnbir](https://cloud.githubusercontent.com/assets/524783/15834484/a16eb436-2c23-11e6-8344-e71b225527a0.png)

Using the RAF `timestamp` argument instead, the animation feels smoother, and the graph is perfectly smooth as well:

![a pen by jo liss g4l3o](https://cloud.githubusercontent.com/assets/524783/15834522/cfc910ec-2c23-11e6-8b41-40083620b9af.png)

I thought that perhaps using the microsecond-resolution `performance.now()` function would improve smoothness, but it doesn't seem to help much:

![a pen by jo liss alfz7](https://cloud.githubusercontent.com/assets/524783/15834570/0669b91c-2c24-11e6-97da-631542d26e12.png)

**Comment by joliss** [comment]
I also opened an issue on the jQuery repo: https://github.com/jquery/jquery/issues/3143

**Comment by Rycochet** [comment]
I'd be interested to see what happens when the browser is under high stress - browsers have (mostly) come on quite a bit since the "old days" when Velocity first came out, and as we're looking to drop legacy browsers anyway this might be worth using - needs thought and talk :-)

**Comment by dalisoft** [comment]
@joliss I'm interested in your CodePen, but i have some xp about web rendering performance, because i use Tween.js (by @sole) since 2011-dec.
So, i highly recommend keep Velociy as is, i tested Velocity for performance, because not trusted in that maybe faster than CSS Transition (in some sites said).
In world have many tweening boss:
Tests: 500bars, 1000ms, repeat, yoyo. (2x Intel CPU, 512Mb GPU);
1. GSAP - i have no words about it, because it's very best ever. (40fps)
2. CreateJS Tween.js (styling) and Tween.js (just tweening) - excellent for performance. (35fps)
3. Velocity - keeps UI smooth, because doesn't overheats site and site running smooth even animation running (30fps, but SMOOTH as Tween.js and GSAP).

Remember, 30fps without lossing frame is better than 60fps with skipping just 2-3 frames.

Please be patient, Chrome 53 improved already. In future new Date().getTIme() will be smooth curves.

If browsers/CPU under stress, `rAF(timestamp)` goes like this
`2300 > 6000 > 8500`
but Velocity timing is
`500 > 516 > 533 > 550 > 566 > 580 > 620`

Thanks for reading this,

I think it's will be useful for you and others.

Thanks to @julianshapiro for Amazing library
Thanks to @sole for Amazing library
Thanks to @GreenSock for Amazing library

**Comment by Rycochet** [comment]
Added an option (default on) to use the high resolution timer when available (browsers have improved a lot in the last couple of years).

Leaving this open until the documentation catches up @kvirani 

---
### Feature: Timestamp

When performing animation each frame uses the time between frames to work out what values to use. There are two ways to do this - ask the clock what time it is, and use the timestamp passed to the *requestAnimationFrame* callback.
Previously Velocity would always ask for the time, but now it will use the timestamp. This results in a smoother animation unless the `progress` callbacks are doing a lot of work - as the timestamp is set once per frame, but asking the time is done separately for every animation that is playing.

If you are doing a lot of heavy work within the callbacks then you can turn off the new behaviour:
```
/* Slow down all animations by a factor of 10. */
$.Velocity.timestamp = false;
```
Turning this off is a global option due to the way Velocity works.

**Comment by Rycochet** [comment]
Btw, thank you @joliss for that awesome codepen and letting us know - Velocity wants performance and quality :-)

**Comment by Rycochet** [comment]
This is no longer an option in V2 - we always care about performance, and shim it if it doesn't exist!
