### ISSUE TITLE
Announcing Velocity's new maintainer, and future plans

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#692]
I stepped away from Velocity a while ago. It was stable and the feature set was robust. I avoided adding more so I could prevent file size bloat and maintenance demands.

But the project is in high use and it warrants an active eye. So, one of my best friends, and the founder and head instructor of Canada's largest coding bootcamp (http://lighthouselabs.ca), is taking over as maintainer of Velocity. He's the real deal.

This is a serious project for him. He's dedicating a large amount of time per week to making sure Velocity stays stable, relevant, sensible, and useful.

His name is @kvirani. We are so very lucky to have him. He's just spent weeks going through the source and he's ready to kick some butt delivering on a promising roadmap for Velocity. He will be consulting with @Rycochet, Velocity's knight in shining armor and an excellent engineer in his own right, to make your investment in this open source project warranted.

Thank you for using Velocity :) It's been an honor.

**Comment by Rycochet** [comment]
Awesome - conversations are happening, and Velocity is getting more love :-D

**Comment by kvirani** [comment]
Thanks for the kind words and warm welcome, @julianshapiro.

I remember when you started working on Velocity (locked away your apartment — a few blocks away from me). Then later when you first announced it publicly. And finally when it exploded in growth from 0 to what it is today. I hope to bring that same level of enthusiasm, energy and skill to it. I'm _incredibly_ excited to be taking this on. Thank you.

Folks, I'll take this opportunity to quickly introduce myself: I've been professionally developing software for the web for ~10 years with of course a big chunk of it focused on JavaScript (alongside Ruby).

I also have a passion for teaching others about programming and technology which I discovered very early by teaching basic DOS and computer usage at the local library when I was only about 8-10 years old (early 90s), back in Pakistan. 

Experimenting with and implementing alternative education models is fascinating to me. That combined with my passion for teaching led me to co-create Lighthouse Labs ~3 years ago, which continues to be my primary focus. I'm very proud with where it has come. In fact, I recently worked on building and launching a new web bootcamp curriculum which has shifted to using JavaScript as the primary language instead of Ruby. I bring this up to point out my proximity and excitement for the JS ecosystem.

I still have a lot to learn about Velocity (as with everything ;) and look forward to working with @Rycochet and other contributors to take it forward. 

Cheers,
Khurram

PS: @julianshapiro expect me to bug you from time to time (read: often ;)

**Comment by lluxx** [comment]
This library lacks essential features like pause and resume. Because performance is needed in graphics intensive applications like for example GAMES. 

My game was suffered in performance, whatever I did to improve it, it was not much. After trying this library I got boost. But lack of pause and resume is killing me, so I can't use it in my game.

**Comment by kvirani** [comment]
Hi @lluxx, thanks for attempting to use Velocity with your game. Please open a [new issue](https://github.com/julianshapiro/velocity/issues/new) on this repo so we can discuss this on a separate thread. It will only take a few minutes and make things more manageable. Thanks!
