### ISSUE TITLE
VMD broken (receiving 301 Moved Permanently)

### ISSUE THREAD

**Issue by garrettlancaster** [julianshapiro/velocity#693]
It appears that VMD is no longer available. Curling the address given in the docs (http://www.julian.com/research/velocity/vmd.min.js) gives a 301 response.

**Comment by Rycochet** [comment]
Think it might have been an internet hiccup, seems ok from here too.

**Comment by garrettlancaster** [comment]
It looks like the VMD bookmarklet in the docs still references julian.com.  The correct address appears to be http://velocityjs.org/vmd.min.js
![untitled](https://cloud.githubusercontent.com/assets/677950/18168053/d086f62e-7021-11e6-9496-fb0885e44f57.jpg)

**Comment by Rycochet** [comment]
Ah, didn't notice that it was the docs site - reopening till fixed :-)

**Comment by kvirani** [comment]
I believe the reason it started working again is b/c I asked @JulianShapiro
to issue a redirect from `julian.com/...` to `velocityjs.org/...` while
maintaining the path requested (instead of just redirecting to the root
path).

The one remaining issue though is that velocityjs.org does not support
https presently, which it needs to for this to be a viable/proper
migration. Otherwise we only have a partial fix.

On it & will update everyone here.
