### ISSUE TITLE
Auto-parameterised values

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#697]
# Premise

A lot of values fed to Velocity are numbers, but quite often they have various bits of text surrounding them. The most obvious things are single number values which often simply have a unit such as "`px`" appended to them.

For animating colours we have more complicated rules in Velocity that split each colour into three (or four) separate attributes, and animate each separately.

For transform values we have multiple attributes that aren't ordered.

Something needs to exist to let us animate these "non-standard" values in such a way as to be logical and extendable.
# Solution

How about simply comparing two strings and parsing out the numbers, then animating those back into the original string instead. That way it would be simple to animate from "`calc(78% - 4em)`" to "`calc(100% - 2em)`" without having to do it as a custom function.

As an added bonus passing a simple transform value would keep the order, and colours could be directly animated.
# Bonus / Gotchas
- Pulling the colour replacement code out could then include all the named web colours translated directly to `rgba(1,2,3)` values (specific attributes would get automatic replacement, anything else can have an exposed function to do it if needed) - currently only a small number of named colours are supported.
- `rgba(red, 0.7)` could be automatically "fixed" to work.
- `rgb` may need to be translated to `rgba` on the fly (with the alpha set to 1).
- Multiple attributes (ie, `box-shadow`) would work directly.
- `transform` could be used directly, the "legacy" separate transform shortcuts could just be added to the transform string in the order they appear.
- First version would need to be force-fed only (transform specifically needs support code to translate the computed css back into the original string).
- Whitespace needs to be ignored.
- Can add pure text values for attributes like `position` that don't need changing, but can revert to initial value after finishing.
- Possibly add automatic unit conversion when a number+unit doesn't match between the start and end (wouldn't be right for `calc` however).
# Pseudo-code

```
if the attribute supports colours
   replace any /(rgba\()?colour(,\d\))?/g with the correct rgb / rgba colour value
endif

for each letter in from and to
   if they are digits
      parseFloat to an array each
      skip all digit characters in source
      if the numbers are the same
         put the number into the format string
      else
         add a %s to the format string
      endif
   else if they are different and neither is a space character
      report an error and end immediately
   else
      add the character to the format string
   endif
endfor
```
## Future
- Support other colour formats such as `hsv()` etc
- Support non-forcefed values (wants testing first)
- ^- Support re-ordering of arguments such as box-shadow:inset on IE / everything else

---
## Potentially Fixes / Related Issues
#677
#459
#650 (possibly)
#625 (needs `mobileHA` to be added to transform)
#562
#561
#543
#506
#471
#466
#403
#388
#263

**Comment by Rycochet** [comment]
This could do with some testing before being promoted to the next minor release - it works simply by taking two strings with differing numbers and animating those numbers.

If you want to change units then using `calc` is the way to go - `$().velocity({left:["calc(50% + 0px)", "calc(0% + 50px)"]});` - making things like this automatic is a future possibility.

**Comment by adailey14** [comment]
I am hitting a bug when animating to 0, I think directly related to this.

I have an animation like this (using velocity-react):
`<VelocityComponent animation={{ marginLeft: !myFlag ? '0%' : '25%' }} duration={300}>`

I've found that the animation breaks when animating from %25 to %0 (%0 to %25 works fine).
I've done some digging, and I see that this is triggering a "pattern", which comes out to calc({0}px + 0%). The start pixel amount is calculated fine, and the end pixel amount is 0.

This ends up creating a tweenContainer with a startValue of [400, 0] (using 400 px for example sake), and endValue of [] (an empty array). The patternReplace code chokes on the empty array endValue. If I change the code below to set an endValue of [0, 0], everything works as expected.

From line 3475 in velocity.js:
```
// Different units, so put into a "calc(from + to)" and animate each side to/from zero
var nStart = parseFloat(tStart),
    nEnd = parseFloat(tEnd);

pattern += (inCalc < 5 ? "calc" : "") + "("
    + (nStart ? "{" + aStart.length + (inRGB ? "!" : "") + "}" : "0") + uStart
    + " + "
    + (nEnd ? "{" + (aStart.length + 1) + (inRGB ? "!" : "") + "}" : "0") + uEnd
    + ")";
if (nStart) {
  aStart.push(parseFloat(tStart));
  aStart.push(parseFloat(0));
}
if (nEnd) { // This results in an empty array because nEnd is 0. If I change it to if (nEnd !== undefined), things work for my case. Not sure if that is the appropriate solution
  aEnd.push(parseFloat(0));
  aEnd.push(parseFloat(tEnd));
}
```

I don't know enough about the code structure in this project to propose the correct fix. Maybe this case shouldn't be hitting the "pattern" code in the first place, since the start and end could be kept in consistent units (either % or pixels).
Let me know if I can provide more information.

**Comment by Rycochet** [comment]
Specifically - the auto-parameterised values are purely for force-feeding right now, it's not supposed to support "normal" values yet as I've not got the time to go through and fix it up for otherwise (specifically there's differences in how the various browsers report things that aren't a single value).

**Comment by adailey14** [comment]
Thanks for the response, can you explain what you mean by force-feeding? 

In my example (<VelocityComponent animation={{ marginLeft: !myFlag ? '0%' : '25%' }} duration={300}>) I wasn't trying to trigger the auto-parameterised functionality, I was just trying to animate a percentage value. This always worked in previous versions, so I thought I would bring it to your attention.

**Comment by Rycochet** [comment]
Ah - shouldn't have triggered without it - http://velocityjs.org/#forcefeeding - it's basically saying "this is the start and end values", rather than taking the "current value". The big issue with the "current value" is that it's always in pixels (unless a previous animation within velocity set it otherwise)...

**Comment by adailey14** [comment]
Ah thanks for the clarification on forcefeeding. 

So I think one of the following things must be happening:

VelocityComponent (part of velocity-react) is triggering forcefeeding. It is forcefeeding a start of 25% and end of 0%. Velocity is converting the 25% to pixels, and leaving the 0% as a percent. The forcefeeding code is choking on the 0% endpoint due to the code I pointed out above.

VelocityComponent is triggering forcefeeding. It is caching/looking up the pixel value of the margin property. It is then passing velocity a start value in pixels, and an end value of 0%. The forcefeeding code is still choking on the 0%.

However it's happening, it still seems to me like there is a bug in the pattern code, since it will provide an empty array as the start or end point when a value is 0.

**Comment by Rycochet** [comment]
Think I got it, it was pushing to `start` *or* `end`, when it should have put them into `start` *and* `end` in pairs. Also realised I was using `parseFloat()` on the same thing twice, so a slight optimisation there too - let me know if the latest push works correctly so I can promote a release :-)

**Comment by adailey14** [comment]
Yes, exactly! That's what I thought but was running my head in circles a bit on the pattern generation code. I will try it out soon - but maybe won't have time until next week.

**Comment by Rycochet** [comment]
That's ok, I'm recovering from the flu, so my brain is a bit slow at things right now ;-)

**Comment by adailey14** [comment]
Rycochet - newbie question if you know - what is the best way to test your commit in my project (which uses NPM to install velocity-react, which in turn installs velocity-animate)?

Do I clone this repository, checkout your commit, maybe build source somehow (maybe not needed?), and then reference the local copy somehow in my package.json? Would I also need to clone velocity-react to have it point to the local version of velocity-animate?

Or alternatively, I could just clone this project directly into my node_modules directory (first removing the copy of velocity-animate that npm installed) - does that make more sense?

**Comment by Rycochet** [comment]
Temporarily do

```
npm install julianshapiro/velocity
```

...then when you've finished testing just do...

```
npm uninstall julianshapiro/velocity
npm install
```

...note that it's not saving either time, just loading locally and going back to the "correct" one after finishing - though do wait till the npmjs version has updated with a new release if you're relying on a bugfix version ;-)

**Comment by adailey14** [comment]
Phew so simple, glad I asked!

**Comment by Rycochet** [comment]
They improved things a lot in the last year ;-)

**Comment by adailey14** [comment]
Just had a chance to test this in my project - and everything is working great.
