### ISSUE TITLE
How to know the state of an animation?

### ISSUE THREAD

**Issue by clem91** [julianshapiro/velocity#733]
Hi,

I tried the new feature pause/resume it works like a charm but I'm wondering if you also implemented a function to retrieve the state (running/paused) ?

**Comment by Rycochet** [comment]
Didn't think of that - needs to have something in there, @codeslaw any ideas?

**Comment by clem91** [comment]
I found an alternative but it's not really "good practice" I store my paused elements in an array and I search everytime I have an action on the element the state. It could be great to have acces to something like $element.velocity().isPaused().

**Comment by Rycochet** [comment]
Would need to have something else since that simply isn't available anywhere other than jQuery (and technically we only support jQuery / Zepto, the interface isn't designed around it).

Thinking something more along the lines of `Velocity(element, "state")` or `$element.velocity("state")` returning an object of true/false values for testing, then it can be extended at a later time:

```javascript
if ($element.velocity("state").paused) {
   ...
}
```

**Comment by codeslaw** [comment]
I like the idea of implementing as `Velocity(element, "state")` because we can store animation state on a per element basis, which eliminates the need to iterate over all calls whenever we need to determine state.

Shouldn't be too difficult to implement, just need to take care to account for delayed elements that were paused before their animation began. I would assume we'd want to treat them no differently than if their animations were moving already?

**Comment by Rycochet** [comment]
Also means we can return the global and local state together - `isPaused`, `elementPause` and `globalPause` - plus no doubt exposing things like `isSVG` etc too...

**Comment by codeslaw** [comment]
Need to address a couple of things. How do we want to handle multiple animations running on the current element? I thought about doing this on a per-call by-element basis, but that doesn't eliminate the problem of multiple animations currently running on the same set of elements. 

We could return state of _all_ animations currently applied to that exact set of elements as an array on the state object, or something like that. Should decide what that looks like before implementing.

**Comment by Rycochet** [comment]
I think most state is per-element, if there are multiple animations on it then they're all either paused or not. For a future extension we need to be able to pause per-queue though (and would need to return an object of `queueName:state`) - but there would still be a generic "this element is ..." state for it.

For an array of elements going in, you'd need an array of results coming out. There could also be "global" results that are the same for everything. Each global could be `true` / `false` / `null` / `undefined`:

* `undefined`: None of the elements have this state.
* `null`: Multiple elements have different state.
* `true`: All the elements are true.
* 'false': All the elements are false.

In Typescript parlance -

```typescript
interface VelocityState {
   globalPause?: boolean | null;
   elementPause?: boolean | null;
   isPaused?: boolean | null;
   isSVG?: boolean | null;
   // ...etc
}

interface VelocityStateList extends VelocityState {
   [index: number]: VelocityState;
}

Velocity(elements: Element[], options: "state"): VelocityStateList;
```

**Comment by Rycochet** [comment]
In v2, the return value of a velocity call can be saved. This can then be queried for information about the current state (and some can be set) using ```anim.velocity("option", "key")``` - see AnimationCall in index.d.ts in the develop branch.
