### ISSUE TITLE
what is the difference between promise and complete?

### ISSUE THREAD

**Issue by lianer** [julianshapiro/velocity#754]
```js
Velocity($('.coin'), {
  left: '+100'
}, {
  duration: 2000, 
  complete: () => console.log('complete')
})
.then(() => console.log('resolve'))

Velocity($('.coin'), 'stop')
```

output:
```
resolve
```

complete not execute

**Comment by ankesh7** [comment]
@lianer The returned promise is resolved when the call's animation completes, regardless of whether it completed on its own or prematurely due to the user calling $element.velocity("stop"[, true]).

The promise is rejected when an invalid first argument is passed into a Velocity call (e.g. an empty properties object or a Velocity command that does not exist). The reject callback is passed the triggered error object.

Complete will only execute on completion of animation. Both of them are applied to different use cases.
