### ISSUE TITLE
Velocity On click And Reverse 

### ISSUE THREAD

**Issue by riiccardo** [julianshapiro/velocity#765]
![untitled](https://cloud.githubusercontent.com/assets/17789047/24079598/c82b78e4-0ca0-11e7-8ac0-89bbbbee1012.png)
Hi julianshapiro i have problem with onclick or onhover or something like that pls help

As the photo shows my problem is in the onclick velocity
show us a way :'(
here this code pen 
[My Code pen](http://codepen.io/riccardo051/pen/oZpMLO)
show what's im saying :'(

**Comment by Rycochet** [comment]
Reverse will reverse the most recent animation to the previous values. When you click once then reverse it will reverse from 5000 -> 0. When you click twice the second click sees the previous value was 5000, so it will reverse with 5000 -> 5000, so no movement.

Either put proper values in, or prevent clicking twice by using `.one()` instead of `.on()`, and re-adding the opposite event when clicked.
