### ISSUE TITLE
Animating transform changing units between percent & px

### ISSUE THREAD

**Issue by luqingxuan** [julianshapiro/velocity#767]
step1. exec code:
``
Velocity(ele, {
translateY:  '-100%'
}, {
duration: 400
}
``

step2. then exec code:
``
Velocity(ele, {
translateY:  '10px'
}, {
duration: 400
}
``

it seems step2 not work, dom style still : transform: translateY(-100%);

is there something i forget? translate from percent to px?

**Comment by Rycochet** [comment]
A JSFiddle would be useful - but I think it's possibly getting confused in the middle of the auto-parameter code. Is it possible for you to use forcefeeding (as that wouldn't cause a problem)? `Velocity(ele, { translateY: ['10px', '-100%'] }, { duration: 400 })`

**Comment by luqingxuan** [comment]
@Rycochet 

Run code:
``
Velocity(ele, { translateY: ['10px', '-100%'] }, { duration: 400 });
``


**i add log in source code (velocity.js  line 1772) ,with Version@1.5.0**

``
switch (transformName.substr(0, transformName.length - 1)) {
/* Whitelist unit types for each transform. */
 case "translate":
invalid = !/(%|px|em|rem|vw|vh|\d)$/i.test(propertyValue);
``
**console.log(propertyValue, invalid);**
``
break;
``

here is the result (**notice log say invalid = true**):

``
calc(-92.24635103068238% + 0.7753648969317618px) true                  
calc(-72.2933040242155% + 2.7706695975784497px) true
calc(-59.33734742278377% + 4.066265257721623px) true
.............................and so on 
calc(-0.00003580512093037669% + 9.999996419487907px) true
calc(0% + 10px) true
``

but with Version@1.2.2, everything goes well.

here is the result(**notice log say invalid = false**):

``
-137.5941616490918px false
-115.6866941459081px false
-97.84197929282249px false
 -75.12960343599049px false
..................................and so on
10px false
``

**Comment by Rycochet** [comment]
That's because it's using the auto-parameter code - in the old code everything was translated to pixel values, which meant that nested animations were impossible to do when using % values. In the new code it can handle anything like that, but you need to use force-feeding (as I said in my earlier reply).

The more technical answer is - `translateY:val` doesn't exist, so Velocity is faking it with 'transform: translateY(val)` (there's a long thread about reading those values back - #269 - but it's not currently possible). If you don't use a forcefeed value then it won't be able to work out what the current value is to animate between them.

As it is now possible to use `Velocity(el, {translate: ["transformY(10px)", "transformY(-100%)"]})` as an argument at some point in the not too distant future it will likely start giving warnings for people to stop using those shortcuts directly.

**Comment by luqingxuan** [comment]
@Rycochet 
maybe u can see this example:
[http://codepen.io/anon/pen/BWPgyr](http://codepen.io/anon/pen/BWPgyr)

i just paste velocity@1.5.0 source code in js script, and exec script:
``
$("div").velocity(
  { translateY: ["10px", "-100%" ] },
  { duration: 2000 }
);
``

even your code:
``
{translate: ["transformY(10px)", "transformY(-100%)"]}
``

but still nothing happened, i have no idea what wrong...

**Comment by Rycochet** [comment]
There's a JSFiddle setup for doing this on, linked in the guidelines you're supposed to read before posting an issue - https://jsfiddle.net/mqv9L27u/ - makes life a lot easier for testing these things.

While your code had a really obvious typo in it, I've tested and it looks like there's some issue with transforming and changing units in there. Unfortunately looks like there's some older code taking effect - and I'm not quite sure where (or when I'll get enough of a chance to look into it).

As a workaround you can add `position:relative;` and it lets you animate the `top` for the same effect.

**Comment by luqingxuan** [comment]
@Rycochet 
ok, thank you for your help.

yeah， i prefer to jsfiddle, 
but u don't know, i come from some place..........,
the net restriction......... so can't enable to access jsfiddle......

the issue is a case when i write vue component, i will wait, and use version@1.2.2 for a short time, but thanks again

**Comment by Rycochet** [comment]
In Velocity V2 unit changes are handled correctly - please note that you must use `transform` directly now as the old shortcuts such as `translateY` no longer exist.
