### ISSUE TITLE
velocity 'finish' just like 'stop' before a new velocity

### ISSUE THREAD

**Issue by vvvhung** [julianshapiro/velocity#794]
I found that if calling a new velocity action right after velocity('finish') then the finishing is the same stopping. Evident: 

https://jsfiddle.net/vvvhung/tern5bv4/1/

So it hard to finish and then start new action continuously. Is it a bug or are there something I missed? Please help.

**Comment by Rycochet** [comment]
Finish will always require a queue - and there you're telling it to not use one so everything overlaps and none of it works as you want. Without the `queue:false` it works exactly as I'd expect it to there...

**Comment by vvvhung** [comment]
Hi Rycochet,
Thanks for your explanation. I saw it works without the queue:false. 

But after trying with custom queue I found another problem. See it here:
https://jsfiddle.net/vvvhung/tern5bv4/4/

It show that after call velocity(finish, queue) then calling dequeue right after will cause 'finish' like 'stop'. But, dequeue is must in case I call them separately (start -> finish -> new). In conclusion, calling "finish and new actions" separately and calling them continuously are still different. This strange behavior make me confuse and that's the reason why I chose queue:false. It's not really easy to code exactly.

Could you explain me this situation?

**Comment by Rycochet** [comment]
I'm actually right in the middle of rewriting it for the v2 beta, and all user access to that has been removed (plus they're actually being treated as separate queues, rather than "first element per animation").

The way Velocity handles subsequent animations can be a little strange internally - but when you call `"finish"` there is no need to `.dequeue()` afterwards as the animation is actually still running - but with a duration of 1ms so it finishes on the next animation tick - any new animation added after the `"finish"` but before the next frame will dequeue automatically.

In other words - it's not acting like `"stop"`, it's acting like a combination of `queue:false` and `"stop"` - and if you add two animations to the queue they will start working in parallel - which would be a bug in your code - but also isn't explicitly stated anywhere in the (badly out of date) docs ;-)

Unfortunately if you call `"finishAll"` then it behaves the same - so adding new animations to the same queue will force multiple ones to dequeue afterwards - one for each currently queued up animation. That would be a bug - but the entire queue code is being rewritten so it's not relevant ;-)

**Comment by vvvhung** [comment]
Yes, in my example without .dequeue() the previous action will finish first. And at least there are two more cases 'finish' work like desire: when it called separately and when using default queue.

Is there any way to finish previous action completely and then do new action with custom queue in a same function? Or I must wait until v2beta?

**Comment by Rycochet** [comment]
If you're only adding a single new animation to the queue then simply add it - no need to dequeue. If you're wanting to add multiple then add one, and use it's `begin:...` callback to add more.

**Comment by vvvhung** [comment]
Thank you very much, I checked for calling dequeue only one at the 1st click action and it works (on local) unless I click very fast ( may be  '1ms' of finish is break) . Don't know why in https://jsfiddle.net  if not dequeue then next action not trigger after waiting the previous finish then click button :(

**Comment by Rycochet** [comment]
I can think of a couple of things to do - but all very hacky - such as checking if the queue is empty before calling finish, and if not then adding a `complete` to the last one (unless a `complete` already exists, in which case add a wrapper to call both original and new functions).

All I can say is v2 is designed to be a lot more logical and easy to use - you'll be able to use the Promise or `complete` of the `"finish"` command when it's actually finished doing stuff - but it's going to be probably at least another month before it gets out of beta (I'm back to being very busy, so only get about one evening a week on it right now)...
