### ISSUE TITLE
fontSize issue

### ISSUE THREAD

**Issue by lbogdan** [julianshapiro/velocity#798]
I'm queuing two animations, the first changes `fontSize` to `1.4em` and the second changes it to `1em`. The first animation is ok, the second somehow starts with a very small `fontSize` (maybe 0?), instead of the size after the first animation, of `1.4em`. An interesting fact is that after the first animation `el.style.fontSize` is `calc(0px + 1.4em)`. Also, using forcefeeding for the second animation (`fontSize: ['1em', '1.4em']`) works.

Am I missing something obvious?

You can check the behavior here: https://codesandbox.io/embed/mql6zw40yx .

**Comment by Rycochet** [comment]
You are - but only if you're psychic or read through the open issues as the documentation is somewhat behind ;-)

When anything (such as Velocity) reads a css value it gets a pixel number (yes, that's simplifying things, but the full answer isn't relevant). Even if it's originally set as another unit. Velocity is trying to animate from that pixel value to an em value, and as such it is trying to use `calc(10px + 0em)` and eventually get to `calc(0px + 1.4em)`.

Using forcefeeding bypasses that pixel value and lets it just animate a single number.

Sadly there's not much that can be done to improve this. Velocity v2 (currently in beta) will behave somewhat better, and will actually work the second way from the second call onwards as it'll remember the values used (rather than the pixel numbers). In the meantime, you can use forcefeeding for anything now, including `box-shadow`, and even multi-layered backgrounds. See #697 for more details on it.

**Comment by Rycochet** [comment]
I should just point out that Velocity v1 can (and does) also change the units used to pixels without forcefeeding - this behaviour is removed in v2, but that won't be ready for normal use for some time yet.

**Comment by lbogdan** [comment]
@Rycochet Thank you for the quick answer. On a related issue, can you also take a look at https://codesandbox.io/embed/vyzmw5nv5 ?

**Comment by lbogdan** [comment]
Also, did it use to work in previous versions? Because the example here https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks seems to work.

**Comment by Rycochet** [comment]
Sorry - got really busy (with being sick meh) - will have a look at earlier versions later, but the behaviour was very different before - it couldn't animated between different units, it just changed everything to a px size and animate that. Basically that means that if some part is dynamic (such as a font size that depended on the device orientation for example) then that would suddenly become static and the animating element would keep the old px value. The new code bypasses that by letting the units stay as part of it - unfortunately as I said earlier, there's no easy way to get the unit value for something short of totally rewriting the css parsing and matching rules - or simply providing the first value as a forcefeeding one.

**Comment by lbogdan** [comment]
@Rycochet No worries, hope you're feeling better! Did you take a look at the second link https://codesandbox.io/embed/vyzmw5nv5? It only uses 'px', but still behaves strange.
