### ISSUE TITLE
Website Error - $(...).velocity is not a function

### ISSUE THREAD

**Issue by mjarpitanand** [julianshapiro/velocity#800]
![image](https://user-images.githubusercontent.com/14835964/30151896-f564d7b4-93ce-11e7-88f2-2f38589eb660.png)
When I click on side menu, it shows error

**Comment by Rycochet** [comment]
> Please make sure any issue Title is actually relevant and useful. Might I also suggest either using the Snipping tool to make a grab of part of the screen, or taking a screenshot of the whole screen. Using the Snipping tool, and then taking a screenshot of the Snipping tool itself isn't any help (and in this case hides the url etc).

The website is out of date, and I have no access to fix it, however it does work properly here, all files loaded, and not having that error anyway. I'd suggest reloading to check if it still happens, and if so then checking other browsers to track down what is going wrong as that issue is definitely at your end and not webserver related.

**Comment by arpitanand112** [comment]
Sorry for not providing details on title.

The issue is resolved, when i opened it in chrome canary, earlier i was using chrome. The site was running successfully.

If you can tell me what all are the possible reasons for the not running in browser, that will be great.
