### ISSUE TITLE
Should I still use velocity.js or is the project dead?

### ISSUE THREAD

**Issue by tsawitzki** [julianshapiro/velocity#829]
I've been an avid user of velocity.js, using it in a dozen projects but currently I wonder if it might be smart to switch to a more recent library which is maintained on a more regular basis. It's been almost 2,5 years now since Julian gave the project away and I am uncertain about its future. Maybe I'm wrong?

**Comment by Rycochet** [comment]
Might I suggest you actually look at the open issues, and see how much work is going into the [develop](https://github.com/julianshapiro/velocity/tree/develop) branch - Velocity is alive and getting major updates, the currently released version is at a dead-end due to the code complexity and time needed to actually do anything with it, and will be moved to a mainenance branch when v2 gets to release (which is running about a month behind right now, so hopefully by the end of January for public beta and moved over to the master branch).
