### ISSUE TITLE
fastdom techniques

### ISSUE THREAD

**Issue by sido420** [julianshapiro/velocity#834]
I was planning to use fastdom for my project and wanted to know if velocity already takes care of such techniques or not.

There are parts of the project that might still benefit from fastdom but was more concerned about animations using velocityjs.

Fastdom: https://github.com/wilsonpage/fastdom

**Comment by Rycochet** [comment]
I'm going to talk about Velocity v2 as that will get a beta release (and moved to the master branch) in less than a week - v1 was mostly like this, but there were several places that it could break the ideas.

In V2 it is far better at doing that than even the fastdom project (though that is due to being an animation library and knowing what is actually going on inside it) - all DOM reads are run at the start of the tick, then all animation updates, and then any callbacks that are outside the control of the library and may potentially read again.

If you look at the [tick.ts](https://github.com/julianshapiro/velocity/blob/develop/src/Velocity/tick.ts#L148) file (link will go dead when it moves to master) file you can see that there are multiple loops for different things - for when it can actually make a change to the data, or access the DOM.

Finally, Velocity has always had a local cache of the DOM properties that slow down on reading (why you don't mix it with other things) - so it's only when adding new animations that there is the possibility of reading directly from the DOM (though animated scrolling is potentially another matter and subject to more annoyances). The only DOM read at a "later" point (ie when it's in the animation tick) is when it can't work out what the start value is - either there is another animation running (so "stop" can cause it to not end where expected), or if there's another animation queued up (in both cases it's on a property basis, so animating "height" won't stop getting the current value for "width").
