### ISSUE TITLE
tween value v2

### ISSUE THREAD

**Issue by numberokta** [julianshapiro/velocity#841]
Tween value in progress function return object.
`JSON.stringify(tweenValue)` return `nothing`
`Object.keys(tweenValue)` return `["element","tweens","_prev","_next","_flags","options","percentComplete","elements","ellapsedTime","timeStart","_nextProgress","tween","_nextComplete"]`

**Comment by Rycochet** [comment]
You're supposed to actually fill in the issue template when you report an issue - in this case it wouldn't have made any difference as you also didn't check the wiki for the arguments which have changed since v1 - https://github.com/julianshapiro/velocity/wiki/Option---Progress

I've just tidied up the formatting slightly, however there is a big note at the bottom with the changes from v1 - specifically the "start" time is no longer passed as it's not a valid timestamp.
