### ISSUE TITLE
Use Velocity.js WithOut jQuery

### ISSUE THREAD

**Issue by riiccardo** [julianshapiro/velocity#867]
Hello Velocity Again 😄 

I See Both Article About using velocity Without jQuery

[sitepoint](https://www.sitepoint.com/how-to-use-velocity-js-without-jquery/) & [smashingmagazine](https://www.smashingmagazine.com/2014/09/animating-without-jquery/)

But I Dont Get Good Result ...

1- velocity hook without jQuery
2- $.Velocity.RunSequence() without jQuery
3- $.queue() and $.delay() without jQuery

SitePoint:
`The Velocity.js UI Pack exposes a function called $.Velocity.RunSequence(), which combines multiple Velocity calls into a a single effect you can then reference by name. This feature would have been super handy when dealing with more complex animation sequences. Unfortunately, I didn’t manage to make it work without jQuery`

`Such a powerful library would have benefited from making available a timeline. Using Tweene could have been a solution, but again, integration between Tweene and Velocity without jQuery is not straightforward`

Velocity Site: http://velocityjs.org/#dependencies 
Using Velocity without jQuery

`Further, when using velocity.js without jQuery and Zepto, you inherently no longer have access to the $.queue() and $.delay() functions provided to you by those libraries.`

Please create another script called: Velocity.vanilla.js ( Velocity WithOut jQuery )

and ur general file velocity.js ( Work With Both jQuery And Javascript )

Thanks 🎉 😍 

And Also we waiting for new version 😢 🤦‍♂️

**Comment by brunoamaral** [comment]
I think I know the code structure you are looking for, but your request isn't clear. Are you trying to do something specific or is this a general request to improve the documentation?

**Comment by riiccardo** [comment]
dude go to both article u will get my mean :|

**Comment by canyoudev** [comment]
@riiccardo you suggest other person to waste his time reading useless articles while you can't formulate your question? Forget about documentation, since v2 is developing with total API changes and you will not get documentation for it any time soon.

**Comment by Rycochet** [comment]
Those articles are out of date - the first is from last year, and the second is actually from 2014 - Velocity V1 hasn't required jQuery for a long time, and the velocityjs.org site is correct in that respect (it used the same basic API for a lot of things, so would let it use the actual jQuery calls if they were available instead).

Saying that, V2 has got no requirement on any other libraries at all. It's happy to patch them if they exist (it knows about jQuery and Zepto), as well as the DOM Elements and anything that can select Elements from the DOM (such as `document.querySelectorAll` etc).

V2 will be out of beta as soon as I get the last couple of days free for working on it - including updated documentation - the basic documentation for it is on the wiki here (https://github.com/julianshapiro/velocity/wiki). There are a list of changes on here - https://github.com/julianshapiro/velocity/blob/master/V2_CHANGES.md - which will be updated and put into the new documentation when it is done.

Just from a pure technological and coding point of view, that final link about Vanilla has the right idea, but goes about it the wrong way. There is still a need for jQuery because there are browser incompatibilities - Chrome added something breaking the standards a year ago - but there were workarounds to it - then Safari added the same thing very recently - without actually supporting the other standards that let you work around it. If you're not aware of what I'm talking about then it's actually better to use a library like jQuery so you don't have to keep yourself informed about that level of problem and can just get on and code (and from a good web server it only adds ~25k of bandwidth using it - we don't have to count bytes quite as much as we used to, and serving from a CDN is even better)...
