### ISSUE TITLE
Issue with dequeue when not using jQuery. Cannot read property 'dequeue' of undefined

### ISSUE THREAD

**Issue by vigneshTheDev** [julianshapiro/velocity#878]
#### Your system information

* VelocityJS version: 2.0.4
* Browser: Chrome
* Operating System: Windows 10

#### Checklist

* Is this an issue with *code*?: Yes
* Is this an issue with *documentation*?: No
* Have you reproduced this in other browsers?: Yes
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

#### Please describe your issue in as much detail as possible:
While using velocity without jQuery, Velocity.Utilities.dequeue has to start the animation. But the Velocity.Utilities is undefined. And the animations are immediately started after the Velocity() call.

#### Steps for reproducing this issue (code):

1. Create custom queues
2. Call Velocity.Utilities.dequeue function

#### JSFiddle example showing issue in action (code):

Fiddle: https://jsfiddle.net/0u419euz/1/

**Comment by Rycochet** [comment]
There is no dequeue method in Velocity V2, nor is there any Utilities member, nor does it have anything whatsoever to do with jQuery

The documentation on the website has almost nothing to do with Velocity V2 - it's now only on the wiki (once V2 gets out of beta it will be updated) - [Option: Queue](https://github.com/julianshapiro/velocity/wiki/Option---Queue)

Briefly - a Queue will start immediately, use `"pause"` on that queue if you want otherwise.
