### ISSUE TITLE
Stopping custom named queue breaks default main queue

### ISSUE THREAD

**Issue by 5andr0** [julianshapiro/velocity#889]
#### Your system information

* VelocityJS version: 1.5.1
* Browser: Firefox/Chrome latest
* Operating System: Win10

#### Checklist

* Is this an issue with *code*?: Yes
* Is this an issue with *documentation*?: No
* Have you reproduced this in other browsers?: Yes
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: No

#### Please describe your issue in as much detail as possible:
Stopping a custom named queue breaks the default queue animation (left to right in my code example).
It resets the animation to an earlier frame, slows down and stops halfway.
Using another custom named queue instead of the main queue would fix it and isn't affected by the stop call.
Using Velocity v2+ also fixes this with its new queue system, however i'd like to stick with 1.5.1 for better browser support. Will you keep updating the pre v2 versions for bug fixes?

#### Steps for reproducing this issue (code):

```
var e = document.getElementById("div1");
e.style.position = 'absolute';

Velocity(e, { left: window.innerWidth}, 5000); // same problem with forcefeeding
Velocity(e, {opacity: 0.5}, {queue: "f", duration: 5000});
Velocity.Utilities.dequeue(e, "f");
setTimeout(function(){Velocity(e, "stop", "f");}, 2000);
```

#### JSFiddle example showing issue in action (code):

https://jsfiddle.net/5andr0/b7hyqLgk/1/

**Comment by Rycochet** [comment]
Sadly this isn't the sort of bug fix that'll be touched in V1 (I can't see many that will as Velocity isn't exactly a security risk) - the queue code in there is basically just jQuery, and the source itself is a single monolithic that is seriously awkward to understand - if you find and fix the issue against the [`v1`](https://github.com/julianshapiro/velocity/tree/v1) branch then I'll be happy to merge, but otherwise it's not going to get looked at.

**Comment by 5andr0** [comment]
I fixed it: https://github.com/julianshapiro/velocity/pull/890
Really looking forward to the v2 extra file for old browser support!
Thanks for your awesome work

**Comment by Rycochet** [comment]
Awesome - I'll merge and update the version number as soon as I can (likely tomorrow evening)!

I need to know what browsers are needed, at the least there'll be some IE fixes, but it won't be able to support as much as V1 simply because standards have moved on so much (so I can polyfill some specific things, but there's a definite limit to them).

**Comment by 5andr0** [comment]
I only use polyfill for older IE on websites with big company clients because most of them are forced to use IE for (stupid) security reasons. All other regular end customers usually have updated browsers of their choice, so its a good thing to ditch browser support for speed and less code! Thanks for merging =)

**Comment by Rycochet** [comment]
And 1.5.2 is now published and out with this fix - thanks! :-)
