### ISSUE TITLE
Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [julianshapiro/velocity#904]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by Rycochet** [comment]
Nope - I'm part-way through changing the testing to use Jest so it can be run on CI, but I've now been at that stage for almost a year due to work/life balance (and just not having the time to do any more on here).

Pretty much all the CI services require a file in the repo to control them - so if you don't see a file it's generally assumed that there's none :-(
